import { chromium, devices } from 'playwright';
const BASE='http://43.132.228.109';
const browser=await chromium.launch();const log=(...a)=>console.log(...a);
// build single workout
const m=await browser.newContext(devices['iPhone 13']);const mp=await m.newPage();
await mp.goto(`${BASE}/`,{waitUntil:'networkidle',timeout:30000});await mp.waitForTimeout(3500);
await mp.locator('.navGroupTrigger',{hasText:'Library'}).first().click();await mp.waitForTimeout(500);
await mp.locator('.navFlyoutItem',{hasText:'Programming'}).first().click();await mp.waitForTimeout(2000);
await mp.locator('.workoutTabMenuTrigger').click();await mp.waitForTimeout(300);
await mp.locator('.workoutTabMenuList button',{hasText:'Program Builder'}).click();await mp.waitForTimeout(1000);
await mp.locator('.mbField select').first().selectOption('Single Workout').catch(()=>{});
await mp.locator('.mbField input').first().fill('ZZ Run Test');
await mp.getByRole('button',{name:/^Next$/}).first().click();await mp.waitForTimeout(600);
await mp.getByRole('button',{name:/Add Exercise/i}).first().click();await mp.waitForTimeout(2500);
await mp.locator('.mobileSheet select').first().selectOption('Cardio');await mp.waitForTimeout(1000);
await mp.locator('.mbSearchInput').fill('treadmill');await mp.waitForTimeout(1200);
await mp.locator('.mobilePickerRow').first().click();
await mp.locator('.mbHeaderAction').click();await mp.waitForTimeout(1500);
await mp.locator('.mobileBuilderActionBar button',{hasText:/^Save$/}).click();await mp.waitForTimeout(4500);
await m.close();
// desktop: check sessions
const d=await browser.newContext({viewport:{width:1366,height:950}});const dp=await d.newPage();
dp.on('response',async r=>{if(r.url().includes('/api/programTemplates')){try{const j=await r.json();log('programTemplates count=',(j.templates||[]).length, r.url().includes('programRecordId')?'(w/recId)':'');}catch{}}});
await dp.goto(`${BASE}/`,{waitUntil:'networkidle',timeout:30000});await dp.waitForTimeout(3500);
await dp.locator('.sidebar').hover();await dp.waitForTimeout(300);
await dp.locator('.navGroupTrigger',{hasText:'Library'}).first().click();await dp.waitForTimeout(300);
await dp.locator('.navFlyoutItem',{hasText:'Programming'}).first().click();await dp.waitForTimeout(1800);
await dp.getByRole('button',{name:/Saved Programs/i}).first().click();await dp.waitForTimeout(2500);
await dp.locator('.programListItem',{hasText:'ZZ Run Test'}).first().click();await dp.waitForTimeout(3000);
log('Program Sessions:',(await dp.locator('.savedProgramSessions').innerText().catch(()=>'n/a')).replace(/\s+/g,' ').slice(0,160));
await d.close();await browser.close();
