import { chromium } from 'playwright';
const b = await chromium.launch();
const p = await b.newPage({ viewport:{width:1400,height:980}, deviceScaleFactor:2 });
await p.goto('http://43.132.228.109/', { waitUntil:'networkidle', timeout:60000 });
await p.waitForTimeout(3000);
await p.mouse.move(40,300); await p.waitForTimeout(700);
const btns = await p.$$('.sidebar button, .sidebar a');
await btns[1].click(); await p.waitForTimeout(1200);
const fly = await p.$('.navFlyout'); if (fly) await p.locator('.navFlyout').getByText('Teams',{exact:true}).click({force:true}).catch(()=>{});
await p.waitForTimeout(2500);
await p.locator('.teamsTableRow').first().click(); await p.waitForTimeout(1500);
await p.locator('.teamDetail .teamMemberName').first().click();
await p.waitForTimeout(1500);
const el = await p.$('.accountTeamList');
const box = await el.boundingBox();
await p.screenshot({ path:'rv_teamrow.png', clip:{x:box.x-10,y:box.y-30,width:box.width+20,height:box.height+50} });
const val = await p.$eval('.accountTeamPosition', e=>e.value).catch(()=>'(none)');
console.log('position input value:', val);
await b.close();
