import { pinyin } from 'pinyin-pro'
import type { CharacterFamily, Phrase } from '../types'

type Member = CharacterFamily['members'][number]
type Example = readonly [hanzi: string, english: string]

const examples: Record<string, Example> = {
  清楚: ['教练把今天的训练计划说得很清楚。', 'The coach explains today’s training plan very clearly.'],
  情况: ['我们先了解你的情况，再决定训练内容。', 'We will understand your condition first, then decide what to train.'],
  请问: ['请问，你的肩膀什么时候开始不舒服？', 'May I ask when your shoulder began to feel uncomfortable?'],
  晴天: ['晴天的时候，我们喜欢去户外攀岩。', 'When it is sunny, we like to climb outdoors.'],
  抱住: ['做这个动作时，先抱住药球。', 'When doing this movement, hold the medicine ball first.'],
  跑步: ['她每周跑步三次，但是每次速度不同。', 'She runs three times a week, but at a different pace each time.'],
  泡沫轴: ['训练以后，他用泡沫轴放松大腿。', 'After training, he uses a foam roller to relax his thighs.'],
  炮弹: ['博物馆里展示着一枚很旧的炮弹。', 'An old artillery shell is displayed in the museum.'],
  妈妈: ['我妈妈周末常常和朋友一起散步。', 'My mom often walks with friends on weekends.'],
  可以吗: ['我们今天把重量降低一点，可以吗？', 'Can we lower the weight a little today?'],
  号码: ['请把你的手机号码写在这里。', 'Please write your phone number here.'],
  骂人: ['有问题可以直接说，但是不要骂人。', 'You can speak directly when there is a problem, but do not curse at people.'],
  健康: ['稳定的睡眠习惯对健康很重要。', 'A stable sleep routine is important for health.'],
  关键: ['动作的关键是保持呼吸和节奏。', 'The key to the movement is maintaining breathing and rhythm.'],
  建立: ['我们正在建立一个更稳定的训练基础。', 'We are building a more stable training foundation.'],
  肌腱: ['肌腱需要时间适应新的训练量。', 'Tendons need time to adapt to new training volume.'],
  健身房: ['我早上七点到健身房上课。', 'I arrive at the gym at seven in the morning to teach.'],
  放松: ['先放松肩膀，然后慢慢呼气。', 'Relax your shoulders first, then breathe out slowly.'],
  预防: ['充分热身可以帮助预防一些运动损伤。', 'A thorough warm-up can help prevent some sports injuries.'],
  访问: ['下周我们会访问一家新的训练中心。', 'Next week we will visit a new training center.'],
  住在: ['我住在离地铁站不远的地方。', 'I live not far from the metro station.'],
  注意: ['深蹲时要注意膝盖和脚尖的方向。', 'During a squat, pay attention to the direction of the knees and toes.'],
  柱子: ['把弹力带固定在那根柱子上。', 'Attach the resistance band to that pillar.'],
  驻地: ['运动员到达比赛驻地以后先休息。', 'After arriving at the competition base, the athlete rests first.'],
  带领: ['今天由马里奥带领大家完成热身。', 'Mario will lead everyone through the warm-up today.'],
  门铃: ['听到门铃以后，请帮我开一下门。', 'When you hear the doorbell, please help me open the door.'],
  零次: ['这个月他零次缺课，每次都准时到。', 'He missed zero sessions this month and arrived on time every time.'],
  冷静: ['比赛开始得不顺利，但她还是很冷静。', 'The race did not start smoothly, but she remained calm.'],
  成功: ['她终于成功完成了第一个引体向上。', 'She finally succeeded in completing her first pull-up.'],
  空间: ['向后走一步，给自己多一点空间。', 'Take one step back and give yourself more space.'],
  长江: ['长江经过很多重要的中国城市。', 'The Yangtze River passes through many important Chinese cities.'],
  红色: ['红色的弹力带比黄色的阻力更大。', 'The red resistance band has more resistance than the yellow one.'],
  米饭: ['训练前两小时，他吃了一碗米饭。', 'Two hours before training, he ate a bowl of rice.'],
  返回: ['完成这一组以后，返回起点休息。', 'After finishing this set, return to the starting point and rest.'],
  平板: ['教练用平板给客户看动作视频。', 'The coach uses a tablet to show the client a movement video.'],
  版本: ['这个版本的计划更适合初学者。', 'This version of the program is more suitable for beginners.'],
  慢一点: ['如果动作不稳定，就做慢一点。', 'If the movement is unstable, do it a little slower.'],
  浪漫: ['他们在一家很浪漫的小餐厅吃晚饭。', 'They have dinner at a very romantic little restaurant.'],
  馒头: ['早餐我吃了一个馒头和两个鸡蛋。', 'For breakfast, I ate a steamed bun and two eggs.'],
  蔓延: ['疼痛开始从肩膀向手臂蔓延。', 'The pain began to spread from the shoulder toward the arm.'],
  上坡: ['上坡跑时不要一开始就太快。', 'When running uphill, do not start too fast.'],
  披上: ['训练结束后，她披上外套离开了。', 'After training, she put on her coat and left.'],
  被影响: ['工作压力很大时，他的睡眠容易被影响。', 'When work stress is high, his sleep is easily affected.'],
  突破: ['这个月她突破了自己的最好成绩。', 'This month she surpassed her personal best.'],
  预订: ['我已经预订了周六下午的攀岩课。', 'I have already booked Saturday afternoon’s climbing class.'],
  头顶: ['把药球举到头顶，但不要耸肩。', 'Raise the medicine ball overhead, but do not shrug.'],
  开灯: ['房间有点暗，请先开灯。', 'The room is a little dark; please turn on the light first.'],
  钉子: ['木板上有一颗钉子，小心不要踩到。', 'There is a nail in the board; be careful not to step on it.'],
  招手: ['看到客户进门时，前台向他招手。', 'When the client entered, the receptionist waved to him.'],
  超过: ['今天的训练时间不要超过一个小时。', 'Today’s training time should not exceed one hour.'],
  介绍: ['开会前，请先介绍一下你的团队。', 'Before the meeting, please introduce your team.'],
  沼泽: ['雨季里，这片土地会变成沼泽。', 'During the rainy season, this land becomes a marsh.'],
  粮食: ['这个地区生产的粮食足够当地人使用。', 'The food crops produced in this region are enough for local people.'],
  海浪: ['今天海浪太大，不适合下水。', 'The ocean waves are too large today, so it is not suitable to enter the water.'],
  训练量: ['最近睡眠不好，所以我们降低了训练量。', 'Sleep has been poor recently, so we reduced the training volume.'],
  灰狼: ['纪录片里的灰狼正在雪地里奔跑。', 'The gray wolf in the documentary is running through the snow.'],
  漂亮: ['这个动作完成得很漂亮，也很稳定。', 'This movement was completed beautifully and steadily.'],
  飘动: ['山顶的旗子在风中不停地飘动。', 'The flag on the mountaintop keeps fluttering in the wind.'],
  目标: ['今天的目标是稳定完成四组。', 'Today’s goal is to complete four sets steadily.'],
  飞镖: ['他第一次玩飞镖就打中了中心。', 'The first time he played darts, he hit the center.'],
  根据: ['我们会根据你的感觉调整重量。', 'We will adjust the weight according to how you feel.'],
  跟着: ['先跟着我做一遍，然后自己试。', 'Follow me once first, then try it yourself.'],
  很好: ['很好，下一组继续保持这个节奏。', 'Very good; keep this rhythm for the next set.'],
  狠心: ['他不忍心拒绝朋友，觉得自己不够狠心。', 'He cannot bear to refuse his friend and feels he is not hard-hearted enough.'],
  可惜: ['可惜今天下雨，我们不能去户外攀岩。', 'Unfortunately it is raining today, so we cannot climb outdoors.'],
  借用: ['我可以借用一下你的弹力带吗？', 'May I borrow your resistance band for a moment?'],
  错误: ['记录重量时，他发现了一个输入错误。', 'While recording the weight, he found an input error.'],
  措施: ['教练采取了措施来降低受伤风险。', 'The coach took measures to reduce injury risk.'],
  星期: ['这个星期我安排了三次中文练习。', 'I scheduled three Mandarin practice sessions this week.'],
  姓名: ['请在表格上填写姓名和电话号码。', 'Please fill in your full name and phone number on the form.'],
  灵活性: ['这个方案有足够的灵活性，可以随时调整。', 'This plan has enough flexibility to be adjusted at any time.'],
  牲畜: ['农场里的牲畜每天早上都要喂。', 'The livestock on the farm must be fed every morning.'],
  学校: ['学校旁边新开了一家健身房。', 'A new gym opened next to the school.'],
  比较: ['和上周比较，今天的动作更稳定。', 'Compared with last week, today’s movement is more stable.'],
  弹力胶带: ['她用弹力胶带保护手指再去攀岩。', 'She uses elastic tape to protect her fingers before climbing.'],
  郊外: ['周末我们坐火车去郊外徒步。', 'On the weekend, we take a train to the countryside to hike.'],
  点菜: ['你先点菜，我来看看喝什么。', 'You order the dishes first; I will see what to drink.'],
  精彩: ['最后一分钟的比赛特别精彩。', 'The final minute of the match was especially exciting.'],
  踩地: ['起身时用整个脚掌踩地。', 'Press the whole foot into the ground as you stand up.'],
  理睬: ['他太专注了，没有理睬旁边的声音。', 'He was so focused that he paid no attention to the sounds beside him.'],
  时间: ['如果有时间，我们最后再练一次。', 'If there is time, we will practice once more at the end.'],
  保持: ['跑步时尽量保持稳定的呼吸。', 'Try to maintain steady breathing while running.'],
  诗歌: ['她喜欢用中文读简单的诗歌。', 'She likes reading simple poetry in Chinese.'],
  服侍: ['他在医院里细心服侍生病的父亲。', 'He carefully attends to his sick father in the hospital.'],
  绕肩: ['热身时先向前绕肩十次。', 'During the warm-up, circle your shoulders forward ten times.'],
  发烧: ['如果你发烧了，今天就不要训练。', 'If you have a fever, do not train today.'],
  知晓: ['客户应该知晓计划改变的原因。', 'The client should be aware of why the plan changed.'],
  翘起: ['平板支撑时不要让臀部翘起。', 'Do not let your hips lift during a plank.'],
  喝水: ['每一轮结束以后都可以喝水。', 'You can drink water after each round.'],
  口渴: ['等到口渴才喝水可能已经太晚了。', 'Waiting until you are thirsty to drink may already be too late.'],
  揭开: ['教练揭开毛巾，检查下面的冰袋。', 'The coach lifts the towel and checks the ice pack underneath.'],
  歇一会儿: ['你看起来有点累，先歇一会儿吧。', 'You look a little tired; rest for a while first.'],
  树枝: ['大风把一根树枝吹到了路上。', 'The strong wind blew a tree branch onto the road.'],
  四肢: ['游泳需要四肢协调配合。', 'Swimming requires coordinated use of all four limbs.'],
  技术: ['力量很重要，但攀岩技术也很重要。', 'Strength is important, but climbing technique is important too.'],
  分歧: ['两位教练有分歧，所以一起看了训练数据。', 'The two coaches disagreed, so they reviewed the training data together.'],
  沟通: ['清楚的沟通可以避免很多误会。', 'Clear communication can prevent many misunderstandings.'],
  疼痛: ['如果疼痛越来越强，请马上停下来。', 'If the pain becomes stronger, stop immediately.'],
  水桶: ['把装满水的水桶提到另一边。', 'Carry the full bucket of water to the other side.'],
  涌出: ['打开阀门以后，水从管子里涌出。', 'After the valve is opened, water surges from the pipe.'],
  药球: ['把药球放在胸前，保持核心稳定。', 'Hold the medicine ball in front of your chest and keep your core stable.'],
  急救: ['每位教练都应该学习基本急救。', 'Every coach should learn basic first aid.'],
  皮裘: ['博物馆里保存着一件古老的皮裘。', 'An old fur garment is preserved in the museum.'],
  泅水: ['他们需要泅水过河才能继续前进。', 'They need to swim across the river to continue forward.'],
  体操: ['她小时候练过五年体操。', 'She practiced gymnastics for five years as a child.'],
  凹槽: ['把这块木板放进对应的凹槽里。', 'Place this board into the matching groove.'],
  遭遇: ['比赛中遭遇困难时，他没有放弃。', 'When he encountered difficulty in the race, he did not give up.'],
  糟糕: ['昨晚睡得很糟糕，今天身体很重。', 'I slept terribly last night, and my body feels heavy today.'],
  英俊: ['照片里的年轻教练看起来很英俊。', 'The young coach in the photo looks handsome.'],
  骏马: ['草原上有一匹骏马正在奔跑。', 'A fine horse is running across the grassland.'],
  严峻: ['这个赛季对新队员来说是严峻的挑战。', 'This season is a severe challenge for the new team members.'],
  竣工: ['新的训练中心预计明年竣工。', 'The new training center is expected to be completed next year.'],
}

export function characterExample(member: Member): Phrase {
  const [hanzi, english] = examples[member.word] ?? [
    `今天我们学习怎么使用“${member.word}”。`,
    `Today we are learning how to use “${member.wordMeaning}.”`,
  ]
  return { hanzi, pinyin: pinyin(hanzi, { toneType: 'symbol', type: 'string' }), english }
}

export function hasAuthoredCharacterExample(word: string) {
  return Object.hasOwn(examples, word)
}
