export const coachReliabilityCopy = {
  en: {
    coachNavClients: "Clients",
    coachNavTeams: "Teams",
    coachNavLibrary: "Library",
    coachNavProgramming: "Programming",
    coachNavBuild: "Build",
    coachNavTests: "Tests",
    coachNavDigital: "Digital",
    coachNavReview: "Review",
    coachNavAdmin: "Admin",
    coachNavCoaches: "Coaches",
    coachNavOrders: "Orders",
    coachNavRevenue: "Revenue",
    coachNavMore: "More",
    coachCircuitSequence: "Complete all {{count}} exercises in order for {{rounds}} rounds.",
    coachAmrapSequence: "Complete as many rounds of these {{count}} exercises as possible in {{minutes}} minutes. Reps are prescribed per round.",
    coachEmomSequence: "Start the next exercise at the beginning of each minute, rotating through {{count}} stations ({{rounds}} rounds). Complete the prescribed reps, then rest for the remainder of the minute.",
    coachAssignOnSave: "Saving assigns this session to {{name}} on {{date}}.",
    coachCircuitAddHint: "Exercises are linked into one circuit in the order you add them. On the first exercise, choose Rounds, AMRAP or EMOM, then set the rounds or duration.",
    coachAddFirstExercise: "Add at least one exercise to this session.",
    coachOffline: "Offline",
    coachReconnected: "Connection restored",
    coachReadFailed: "Could not refresh training",
    coachConnectionHint: "Previously loaded information stays visible. Refresh to check the latest saved changes; unsent edits are not published automatically.",
    coachLastRead: "Last loaded at {{time}}.",
    coachRelatedDataFailed: "Some athlete details could not refresh. Loaded workouts are still available.",
    coachReviewReadFailed: "Some review items could not refresh. Previously loaded items are still shown. Tap Refresh to try again.",
    coachReplyDraftSaved: "Unsent replies and notes saved on this device",
    coachReplyDraftProblem: "Unsent replies need attention",
    coachReplyFailed: "Could not send or save the reply. Your text is retained; check your connection and try again.",
    coachWriteReplyFirst: "Write a reply first.",
    coachReplySent: "Reply sent.",
    coachVideoReviewed: "Video reviewed.",
    coachCalendarZone: "Training dates follow China time (UTC+8).",
    coachNotifications: "Notifications",
    coachNotificationsEmpty: "No notifications yet.",
    coachNotificationsHint: "Recent in-app activity and updates.",
    coachNotificationsError: "Notifications could not refresh. Your previous list is retained.",
    coachNotificationAthlete: "Open athlete",
    calendarWorkoutIsolatedHint: "This athlete, this session only. The library and other assignments stay unchanged.",
    sessionAlreadyStarted: "This session has already started or been completed. Its prescription is preserved. Create a new session for further changes.",
    sessionUnavailable: "Could not load this assigned session. Refresh the calendar and try again.",
    sessionChanged: "The saved session has changed. Your draft is retained. Save again to review the latest version.",
    recoveryTitle: "Review updated session",
    recoveryHint: "The saved session changed while you were editing. Your additions and changes to separate exercises are combined below. Review before publishing.",
    recoveryChoose: "Both versions changed this item. Choose which to keep.",
    recoveryMine: "My edits",
    recoveryLatest: "Latest saved",
    recoveryRemoved: "Removed / empty",
    recoveryPreview: "Session to publish",
    recoverySets: "{{count}} sets",
    recoverySets_one: "{{count}} set",
    recoverySets_other: "{{count}} sets",
    recoverySet: "Set {{count}}",
    recoveryLoad: "Load",
    recoveryTempo: "Tempo",
    recoveryPublish: "Publish reviewed changes",
    recoveryPublishing: "Publishing…",
    recoveryContinue: "Continue editing",
    recoveryField_sessionName: "Session name",
    recoveryField_sessionNameCn: "Chinese session name",
    recoveryField_sessionType: "Session type",
    recoveryField_sessionGoal: "Session goal",
    recoveryField_sessionGoalCn: "Chinese session goal",
    recoveryField_sessionNotes: "Session notes",
    recoveryField_estimatedDuration: "Duration",
    recoveryField_intensity: "Intensity",
    recoveryField_isSingleWorkout: "Session format",
    recoveryField_testTemplateId: "Test battery",
    recoveryField_exercises: "Exercise list and order",
    builderLeaveTitle: "Leave this session?",
    builderLeaveHint: "Publish your changes now, or keep a draft on this device to finish later.",
    builderLeaveSave: "Save and return",
    builderLeaveKeep: "Keep draft and leave",
    sessionSaveFailed: "Could not save the session. Your edits are retained; check your connection and try again.",
    sessionNeedsExercises: "Add at least one exercise before saving this session.",
    assignedSessionSaved: "Saved for this athlete and this session only.",
    coachDraftRecovered: "Unfinished coaching drafts ({{count}})",
    coachDraftLocalOnly: "Saved on this device. Resume to review and save your changes for athletes.",
    coachDraftResume: "Resume draft",
    coachDraftDiscard: "Discard",
    coachDraftDiscardConfirm: "Discard this device draft? This cannot be undone. Saved training stays unchanged.",
    coachDraftSavedLocally: "Draft saved on this device · not published",
    coachDraftSaving: "Changes not yet saved",
    coachDraftUnavailable: "Device draft unavailable · keep this page open",
    coachDraftConflict: "Draft changed in another tab · keep this page open",
    coachDraftUntitled: "Untitled coaching draft",
    coachDraftClientUnavailable: "This draft’s athlete could not be found. Refresh the roster before resuming.",
    coachDraftRestored: "Draft restored. Review it, then save to update training.",
    coachDraftLeaveConfirm: "Discard these unsaved changes and their device draft? Cancel to keep editing or save first.",
  },
  zh: {
    coachNavClients: "运动员",
    coachNavTeams: "团队",
    coachNavLibrary: "训练库",
    coachNavProgramming: "训练编排",
    coachNavBuild: "编排",
    coachNavTests: "测试",
    coachNavDigital: "数字课程",
    coachNavReview: "待处理",
    coachNavAdmin: "管理",
    coachNavCoaches: "教练",
    coachNavOrders: "订单",
    coachNavRevenue: "营收",
    coachNavMore: "更多",
    coachCircuitSequence: "按顺序完成全部 {{count}} 个动作，共进行 {{rounds}} 轮。",
    coachAmrapSequence: "在 {{minutes}} 分钟内，按顺序完成这 {{count}} 个动作，尽可能完成更多轮。每个动作的次数为每轮目标。",
    coachEmomSequence: "每分钟开始时进行下一个动作，在 {{count}} 个训练站之间依次轮换（共 {{rounds}} 轮）。完成规定次数后，在该分钟剩余时间内休息。",
    coachAssignOnSave: "保存后，将此训练安排给 {{name}}，日期为 {{date}}。",
    coachCircuitAddHint: "添加的动作将按顺序组成一个循环。在第一个动作中选择固定轮数、限时尽可能多轮（AMRAP）或每分钟启动（EMOM），再设置轮数或时长。",
    coachAddFirstExercise: "请为本次训练添加至少一个动作。",
    coachOffline: "当前离线",
    coachReconnected: "网络已恢复",
    coachReadFailed: "训练刷新失败",
    coachConnectionHint: "已加载的信息仍会保留。请刷新以查看最新保存的内容；未发送的修改不会自动发布。",
    coachLastRead: "上次加载时间：{{time}}。",
    coachRelatedDataFailed: "部分学员信息暂时无法刷新，已加载的训练仍可查看。",
    coachReviewReadFailed: "部分待处理事项刷新失败，当前仍显示已加载的内容。请点击刷新重试。",
    coachReplyDraftSaved: "未发送的回复和备注已保存在本设备",
    coachReplyDraftProblem: "请检查未发送的回复",
    coachReplyFailed: "回复发送或保存失败，文字已保留。请检查网络后重试。",
    coachWriteReplyFirst: "请先填写回复。",
    coachReplySent: "回复已发送。",
    coachVideoReviewed: "视频已完成点评。",
    coachCalendarZone: "训练日期按中国时间（UTC+8）计算。",
    coachNotifications: "通知",
    coachNotificationsEmpty: "暂无通知。",
    coachNotificationsHint: "近期应用内动态与更新。",
    coachNotificationsError: "通知刷新失败，已保留原有列表。",
    coachNotificationAthlete: "查看学员",
    calendarWorkoutIsolatedHint: "仅修改这位学员的本次训练，不影响动作库、课次模板或其他训练安排。",
    sessionAlreadyStarted: "本次训练已开始或已完成，训练处方将保留。需要调整时，请新建一次训练。",
    sessionUnavailable: "无法加载本次训练，请刷新日历后重试。",
    sessionChanged: "训练内容已更新，草稿已保留。请再次点击保存，核对最新版本。",
    recoveryTitle: "核对更新后的训练",
    recoveryHint: "编辑期间，已保存的训练发生了更新。下方已合并新增动作和互不冲突的修改，请核对后发布。",
    recoveryChoose: "两个版本都修改了此项，请选择要保留的内容。",
    recoveryMine: "我的修改",
    recoveryLatest: "最新已保存版本",
    recoveryRemoved: "已删除／空白",
    recoveryPreview: "即将发布的训练",
    recoverySets: "{{count}}组",
    recoverySets_one: "{{count}}组",
    recoverySets_other: "{{count}}组",
    recoverySet: "第{{count}}组",
    recoveryLoad: "负重",
    recoveryTempo: "动作节奏",
    recoveryPublish: "发布核对后的修改",
    recoveryPublishing: "正在发布…",
    recoveryContinue: "继续编辑",
    recoveryField_sessionName: "课次名称",
    recoveryField_sessionNameCn: "中文课次名称",
    recoveryField_sessionType: "训练类型",
    recoveryField_sessionGoal: "训练目标",
    recoveryField_sessionGoalCn: "中文训练目标",
    recoveryField_sessionNotes: "课次说明",
    recoveryField_estimatedDuration: "预计时长",
    recoveryField_intensity: "训练强度",
    recoveryField_isSingleWorkout: "课次形式",
    recoveryField_testTemplateId: "测试组合",
    recoveryField_exercises: "动作列表及顺序",
    builderLeaveTitle: "离开本次训练？",
    builderLeaveHint: "可以立即发布修改，也可以将草稿保存在本设备，稍后继续编辑。",
    builderLeaveSave: "保存并返回",
    builderLeaveKeep: "保留草稿并离开",
    sessionSaveFailed: "保存失败，修改已保留。请检查网络后重试。",
    sessionNeedsExercises: "请至少添加一个动作后再保存。",
    assignedSessionSaved: "已保存，仅更新这位学员的本次训练。",
    coachDraftRecovered: "未完成的训练草稿（{{count}}）",
    coachDraftLocalOnly: "草稿保存在本设备。继续编辑并保存后，学员才能看到修改。",
    coachDraftResume: "继续编辑",
    coachDraftDiscard: "删除草稿",
    coachDraftDiscardConfirm: "确定删除本设备上的草稿？此操作无法撤销，已保存的训练不受影响。",
    coachDraftSavedLocally: "草稿已保存到本设备 · 尚未发布",
    coachDraftSaving: "修改尚未保存",
    coachDraftUnavailable: "无法保存本地草稿，请勿关闭页面",
    coachDraftConflict: "其他标签页已更新草稿，请勿关闭本页面",
    coachDraftUntitled: "未命名训练草稿",
    coachDraftClientUnavailable: "未找到草稿对应的学员，请刷新学员列表后重试。",
    coachDraftRestored: "草稿已恢复。请检查内容并保存，以更新训练。",
    coachDraftLeaveConfirm: "确定放弃尚未保存的修改并删除本地草稿？可取消以继续编辑，或先保存。",
  },
};
