export const coachReliabilityCopy = {
  en: {
    calendarWorkoutIsolatedHint: "This athlete, this session only. The library and other assignments stay unchanged.",
    sessionAlreadyStarted: "This session has already started or been completed. Its prescription is preserved. Create a new session for further changes.",
    sessionUnavailable: "Could not load this assigned session. Refresh the calendar and try again.",
    sessionChanged: "The saved session has changed since you opened it. Your draft is retained. Reopen the latest version before saving changes.",
    sessionSaveFailed: "Could not save the session. Your edits are retained; check your connection and try again.",
    sessionNeedsExercises: "Add at least one exercise before saving this session.",
    assignedSessionSaved: "Saved for this athlete and this session only.",
    coachDraftRecovered: "Unfinished coaching drafts ({{count}})",
    coachDraftLocalOnly: "Saved on this device. Resume to review and save your changes for athletes.",
    coachDraftResume: "Resume draft",
    coachDraftDiscard: "Discard",
    coachDraftDiscardConfirm: "Discard this device draft? This cannot be undone. Saved training stays unchanged.",
    coachDraftSavedLocally: "Draft saved on this device · not published",
    coachDraftSaving: "Changes not yet saved",
    coachDraftUnavailable: "Device draft unavailable · keep this page open",
    coachDraftConflict: "Draft changed in another tab · keep this page open",
    coachDraftUntitled: "Untitled coaching draft",
    coachDraftClientUnavailable: "This draft’s athlete could not be found. Refresh the roster before resuming.",
    coachDraftRestored: "Draft restored. Review it, then save to update training.",
    coachDraftLeaveConfirm: "Discard these unsaved changes and their device draft? Cancel to keep editing or save first.",
  },
  zh: {
    calendarWorkoutIsolatedHint: "仅修改这位学员的本次训练，不影响动作库、课次模板或其他训练安排。",
    sessionAlreadyStarted: "本次训练已开始或已完成，训练处方将保留。需要调整时，请新建一次训练。",
    sessionUnavailable: "无法加载本次训练，请刷新日历后重试。",
    sessionChanged: "训练内容已被更新，草稿已保留。请重新打开最新版本后再保存修改。",
    sessionSaveFailed: "保存失败，修改已保留。请检查网络后重试。",
    sessionNeedsExercises: "请至少添加一个动作后再保存。",
    assignedSessionSaved: "已保存，仅更新这位学员的本次训练。",
    coachDraftRecovered: "未完成的训练草稿（{{count}}）",
    coachDraftLocalOnly: "草稿保存在本设备。继续编辑并保存后，学员才能看到修改。",
    coachDraftResume: "继续编辑",
    coachDraftDiscard: "删除草稿",
    coachDraftDiscardConfirm: "确定删除本设备上的草稿？此操作无法撤销，已保存的训练不受影响。",
    coachDraftSavedLocally: "草稿已保存到本设备 · 尚未发布",
    coachDraftSaving: "修改尚未保存",
    coachDraftUnavailable: "无法保存本地草稿，请勿关闭页面",
    coachDraftConflict: "其他标签页已更新草稿，请勿关闭本页面",
    coachDraftUntitled: "未命名训练草稿",
    coachDraftClientUnavailable: "未找到草稿对应的学员，请刷新学员列表后重试。",
    coachDraftRestored: "草稿已恢复。请检查内容并保存，以更新训练。",
    coachDraftLeaveConfirm: "确定放弃尚未保存的修改并删除本地草稿？可取消以继续编辑，或先保存。",
  },
};
