// Shared English/Chinese labels for coaching workflows.
export const coachPolishCopy = {
  "en": {
    "polishRoundsceea": "Rounds",
    "polishTimeCapMin4422": "Time cap (min)",
    "polishTotalMindfea": "Total (min)",
    "polishAllCategories060b": "All categories",
    "polishDigitalProgramsf261": "Digital programs",
    "polishBundles9a03": "Bundles",
    "polishAddOns41b6": "Add-ons",
    "polishOnlineCoaching7105": "Online coaching",
    "polishInPersonTraining014b": "In-person training",
    "polishInternalGeneralffaa": "Internal / general",
    "polishTitle768e": "Title",
    "polishLevel7c7f": "Level",
    "polishFocusfe7f": "Focus",
    "polishType3deb": "Type",
    "polishCreatedBy43de": "Created By",
    "polishActionsc3cd": "Actions",
    "polishLoading33ce": "Loading…",
    "polishBuilderQuickNavigationac07": "Builder quick navigation",
    "polishWeekc0ee": "week",
    "polishGoal9fe0": "Goal",
    "polishEGBuildMuscle8d3c": "e.g. Build muscle",
    "polishDuration1370": "Duration",
    "polishPhasef637": "Phase",
    "polishEGFoundation9fd3": "e.g. Foundation",
    "polishSport1855": "Sport",
    "polishEGClimbingc373": "e.g. Climbing",
    "polishBeginner6057": "Beginner",
    "polishIntermediateb1cf": "Intermediate",
    "polishAdvanced4d06": "Advanced",
    "polishElite6f28": "Elite",
    "polishProgramType7dbe": "Program Type",
    "polishAssignTocc79": "Assign to",
    "polishInternalGenerala16d": "Internal (general)",
    "polishClient1bdd": "Client",
    "polishTeam2188": "Team",
    "polishSelectClient0765": "Select client…",
    "polishSelectTeam5c98": "Select team…",
    "polishDay987b": "Day",
    "polishWeekf82b": "Week",
    "polishDa3aa": "d ·",
    "polishSets23fe": "sets ·",
    "polishExe066": "ex",
    "polishDuplicate972d": "Duplicate",
    "polishUnsaved2ab0": "Unsaved",
    "polishEditSessionaca3": "Edit session",
    "polishDuplicateToNextWeek8423": "Duplicate to next week",
    "polishRemoveSessiona72e": "Remove session",
    "polishPhysicalTestdc27": "Physical Test",
    "polishNoExercisesYet71ff": "No exercises yet",
    "polishAdd61cc": "Add",
    "polishCurrentSessionWeek39df": "Current Session · Week",
    "polishDay2ad3": "· Day",
    "polishCloseEditor3ada": "Close editor",
    "polishAlsoSaveToSessionLibraryb1b8": "Also save to Session Library",
    "polishWorkoutName7adc": "Workout Name",
    "polishSessionNamec78b": "Session Name",
    "polishSessionName650a": "Session Name (中文)",
    "polishEstDurationMinfd26": "Est. Duration (min)",
    "polishSessionType3833": "Session Type",
    "polishIntensity0ad6": "Intensity",
    "polishLowa124": "Low",
    "polishModerateea8b": "Moderate",
    "polishHighb1a5": "High",
    "polishMaxa95e": "Max",
    "polishRecoveryea92": "Recovery",
    "polishSessionGoald948": "Session Goal",
    "polishPrimaryFocus319f": "Primary focus...",
    "polishInsertSavedSessioncc09": "Insert saved session",
    "polishFromProgram794d": "From program…",
    "polishPickASession52ec": "Pick a session…",
    "polishAll6a72": "All",
    "polishSets2ab2": "Sets",
    "polishReps7020": "Reps",
    "polishRestEG90Secb7e4": "Rest e.g. 90 sec",
    "polishApplyToc76e": "Apply to",
    "polishDragYourSessionIntoShape137c": "Drag your session into shape",
    "polishAddExercisesToBuildThisSession07d5": "Add exercises to build this session.",
    "polishAddExercise3ca5": "+ Add Exercise",
    "polishExercises4dc5": "Exercises",
    "polishSections7ff5": "Sections",
    "polishSearchExerciseLibrary09bf": "Search exercise library...",
    "polishFilterByEquipmentc44b": "Filter by equipment",
    "polishAllEquipmentf3df": "All equipment",
    "polishCancel77df": "Cancel",
    "polishCreateExerciseb53a": "Create Exercise",
    "polishNewToTheLibrarySavedANDAddedToThisSessiona5dc": "New to the library — saved AND added to this session",
    "polishLoadingExercisesd973": "Loading exercises...",
    "polishNoExercisesMatchThisSearch1df8": "No exercises match this search.",
    "polishExerciseOrderbc78": "Exercise Order",
    "polishActiveSection34db": "Active section:",
    "polishChooseASection87f5": "Choose a section",
    "polishNewExercisesWillBeAddedUnderTheSelectedSection2263": "New exercises will be added under the selected section.",
    "polishCustomSection8a73": "Custom section",
    "polishReturnToSportFingerboardd854": "Return to sport, Fingerboard...",
    "polishUse1d4d": "Use",
    "polishColourf285": "Colour",
    "polishChooseAnExerciseFromTheLeftToAddItToThisSessionb592": "Choose an exercise from the left to add it to this session.",
    "polishLinkeda089": "Linked",
    "polishLinkTheseExercisesAsASupersetAlternateSets047c": "Link these exercises as a superset (alternate sets)",
    "polishLinkSuperset7988": "Link superset",
    "polishLinkTheseExercisesAsACircuitRoundsOfEveryExerciseBackToBack40f1": "Link these exercises as a circuit (rounds of every exercise back-to-back)",
    "polishLinkCircuit4dda": "Link circuit",
    "polishLabel7434": "Label",
    "polishSetAutomaticallyTheLetterAndColourComeFromTheSectionTheNumberFrom0d68": "Set automatically — the letter and colour come from the Section, the number from order. Change the Section to change the letter/colour.",
    "polishSectionf2c6": "Section",
    "polishAccessory9624": "Accessory",
    "polishOrder1d75": "Order",
    "polishCollapseExerciseOrderbfee": "Collapse exercise order",
    "polishWorkSets125a": "Work sets",
    "polishMinb6c9": "min",
    "polishEstDurationdca1": "Est. duration",
    "polishTempo8996": "Tempo",
    "polishRestb79e": "Rest",
    "polishEdit5301": "Edit",
    "polishAccessoryFordd2d": "Accessory for",
    "polishBuilderType18e9": "Builder type",
    "polishSingleWorkout8b3d": "Single Workout",
    "polishMultiDayProgram407f": "Multi-Day Program",
    "polishOptional0c6c": "Optional",
    "polishSessionName9dd6": "Session name",
    "polishEGLowerStrength497a": "e.g. Lower Strength",
    "polishNextbc98": "Next",
    "polishViewProgram2e88": "View program ›",
    "polishDetailsa328": "‹ Details",
    "polishAddExercisesa4ef": "Add Exercises",
    "polishAddExercise0ca1": "Add Exercise",
    "polishLinkAsSupersetf478": "+ Link as superset",
    "polishLinkAsCircuit37b2": "+ Link as circuit",
    "polishExerciseOptionsb4ed": "Exercise options",
    "polishAdd109b": "+ Add",
    "polishArrangecfdd": "Arrange",
    "polishSelectExercisesc770": "Select exercises",
    "polishBackb52b": "Back",
    "polishSearchExercisec4cc": "Search exercise…",
    "polishLoadingExercisesd450": "Loading exercises…",
    "polishNoExercisesMatch16db": "No exercises match.",
    "polishArrangeExercises94f0": "Arrange exercises",
    "polishDonee9b4": "Done",
    "polishSupersetd568": "Superset",
    "polishSelectSavedSessionea91": "Select saved session",
    "polishInsertSessionb53b": "Insert session",
    "polishFromProgram22b1": "From program",
    "polishChooseAProgram45d8": "Choose a program…",
    "polishLoadingSessions3164": "Loading sessions…",
    "polishNoSessionsInThisProgramf4b6": "No sessions in this program.",
    "polishExercises0ee6": "exercises",
    "polishChange64fb": "Change",
    "polishViewExercise6a3d": "View exercise",
    "polishDeletef6fd": "Delete",
    "polishFullSetDetailLoad1RMTempoResta800": "Full set detail — load, %1RM, tempo, rest",
    "polishAlternates90d6": "Alternates ·",
    "polishSwapsTheAthleteCanUseInsteadOfThisExercisee604": "Swaps the athlete can use instead of this exercise.",
    "polishNoAlternatesYetc3dc": "No alternates yet.",
    "polishMoveUpb4f5": "Move up",
    "polishMoveDown260f": "Move down",
    "polishSearchToAddAnAlternate2546": "Search to add an alternate…",
    "polishNoMatches0be6": "No matches.",
    "polishAllForms04f4": "All forms",
    "polishSearchForms9253": "Search forms...",
    "polishItems44d2": "Items",
    "polishNoSavedFormsYetCreateOneToAssignToClients2172": "No saved forms yet. Create one to assign to clients.",
    "polishNoFormsMatchYourSearch3ae9": "No forms match your search.",
    "polishQuestionsff3d": "questions",
    "polishDuplicateForm4a5d": "Duplicate form",
    "polishDeleteForme51f": "Delete form",
    "polishForms4bec": "Forms",
    "polishFormQuestionnaireBuilder9b72": "Form & Questionnaire Builder",
    "polishBuildCheckInsIntakeFormsReadinessSurveysAndCustomQuestionnairesFo1d31": "Build check-ins, intake forms, readiness surveys, and custom questionnaires for coach assignment.",
    "polishSavedForms370a": "Saved Forms",
    "polishReloadcce7": "Reload",
    "polishLoadingFormsc68a": "Loading forms...",
    "polishNoSavedFormsYet6be8": "No saved forms yet.",
    "polishTemplateActionsa931": "Template actions",
    "polishFormName3baf": "Form Name",
    "polishCheckIn4843": "Check-in",
    "polishQuestionnaire42d2": "Questionnaire",
    "polishIntaked9e7": "Intake",
    "polishReadiness6dc1": "Readiness",
    "polishCustom081a": "Custom",
    "polishQuestions9a1f": "Questions",
    "polishAddQuestion1475": "+ Add Question",
    "polishQuestion002f": "Question",
    "polishQuestionTextdda9": "Question text",
    "polishTextc332": "Text",
    "polishLongText3afc": "Long Text",
    "polishNumberb7ba": "Number",
    "polishScalea29f": "Scale",
    "polishSingleSelectc17b": "Single Select",
    "polishMultiSelect9ffa": "Multi Select",
    "polishYesNo9f62": "Yes/No",
    "polishDateeb9a": "Date",
    "polishRequiredeed6": "Required",
    "polishRemovee963": "Remove",
    "polishReviewe29a": "Review",
    "polishClientCommentsFormTestSubmissionsMissedTasksAndOrderFollowUpsThat49cd": "Client comments, form & test submissions, missed tasks, and order follow-ups that need a coach decision.",
    "polishNeedsADecision83ce": "Needs a decision",
    "polishOpenItemsAcross7QueuesWaitingOnYou9df6": "open items across 7 queues waiting on you",
    "polishNoUnansweredMessagesb36c": "No unanswered messages. 👍",
    "polishReplyToYourAthlete7e23": "Reply to your athlete…",
    "polishSendReplyMarkReviewed51d8": "Send reply & mark reviewed",
    "polishNoCheckInsWaitingForAReply7351": "No check-ins waiting for a reply.",
    "polishReviewReply05e1": "Review & reply →",
    "polishOpencf9b": "Open",
    "polishArchive2621": "Archive",
    "polishWorkoutCommentc988": "Workout comment",
    "polishOpenClient9da0": "Open Client",
    "polishNoCommentsOrOrderReviewsWaitingb922": "No comments or order reviews waiting.",
    "polishOnThisPagee1fc": "on this page",
    "polishMissedWorkout3195": "Missed workout",
    "polishNoMissedWorkoutsNeedAttention56df": "No missed workouts need attention.",
    "polishSearchSubmissions849c": "Search submissions",
    "polishSearchAthleteOrAssessmentd6e1": "Search athlete or assessment…",
    "polishSubmissionStatus6698": "Submission status",
    "polishNeedsReview33a5": "Needs review",
    "polishReviewed31ef": "Reviewed",
    "polishAllSubmissions4ff2": "All submissions",
    "polishNoMatchingFormOrTestSubmissionsc32c": "No matching form or test submissions.",
    "polishDailyCheckIn35af": "Daily check-in",
    "polishSubmitted2e00": "Submitted",
    "polishCloseCheckInReview4d6d": "Close check-in review",
    "polishYourReplybf9a": "Your reply",
    "polishUpcomingWorkouts1a28": "Upcoming Workouts",
    "polishDayd420": "• Day",
    "polishChooseDatee787": "Choose date",
    "polishAssignTaska96a": "Assign Task",
    "polishProgram9d68": "Program",
    "polishStartDate9d7a": "Start Date",
    "polishArrangeWorkouts4458": "Arrange Workouts",
    "polishPastedb24": "Paste",
    "polishAddProgramOrSession623a": "Add program or session",
    "polishOpenAssignment82fa": "Open assignment",
    "polishDragToAnotherDateOrTapToOpen968d": "Drag to another date or tap to open",
    "polishPreviousMonth46a2": "Previous month",
    "polishNextMonth8abf": "Next month",
    "polishAddItemToThisDateae8d": "Add item to this date",
    "polishClosebbfa": "Close",
    "polishSelect8598": "Select",
    "polishNoSessionsYet9d77": "No sessions yet",
    "polishAthleteSCalendarc77c": "Athlete's calendar",
    "polishCopyPortalLink8847": "Copy portal link",
    "polishRostere551": "Roster",
    "polishClients28e2": "Clients",
    "polishYourAthletesAtAGlanceEngagementAttentionFlagsAndQuickActions01af": "Your athletes at a glance — engagement, attention flags, and quick actions.",
    "polishAddClient4b57": "Add client",
    "polishActiveAthletes78e2": "Active athletes",
    "polishTrainingWithYouNow24ed": "training with you now",
    "polishOnline2dbc": "online",
    "polishInPerson2883": "in-person",
    "polishTeams4629": "teams",
    "polishNeedAttention46d0": "Need attention",
    "polishAthletesFlagged3386": "athletes flagged",
    "polishAverageComplianceThisWeekee2a": "average compliance this week.",
    "polishClientStatusFiltersae1f": "Client status filters",
    "polishSearchClientsb50b": "Search clients",
    "polishSearchClient11f1": "Search client…",
    "polishGroupClientsc8ff": "Group clients",
    "polishNoGroupinga0d0": "No grouping",
    "polishOnlinec3e8": "Online",
    "polishInPersone1d7": "In-person",
    "polishFilterClientStatusc123": "Filter client status",
    "polishAllStatuses6405": "All statuses",
    "polishFilterByCoach589a": "Filter by coach",
    "polishAllCoaches4f5b": "All Coaches",
    "polishRefresh56e3": "Refresh",
    "polishAttentionFilters00f6": "Attention filters",
    "polishNeedsAttentiona126": "Needs attention",
    "polishShowAll50a2": "Show all",
    "polishSelected835f": "selected",
    "polishAssignProgram52dc": "Assign program",
    "polishAddToTeamb445": "Add to team",
    "polishAddTage0db": "Add tag",
    "polishCopyLinksd68a": "Copy links",
    "polishClear719e": "Clear",
    "polishSelectProgramb398": "Select program…",
    "polishTagNamefcf2": "Tag name",
    "polishLoadingClients527e": "Loading clients…",
    "polishNoClientsMatch7494": "No clients match",
    "polishTryADifferentBucketFilterOrSearch71dd": "Try a different bucket, filter, or search.",
    "polishAthleteaa86": "Athlete",
    "polishEngagement4b1f": "Engagement",
    "polishAttention74e0": "Attention",
    "polishOpenClientHome238c": "Open client home",
    "polishThisWeek7b72": "This week",
    "polishCompliance68f0": "Compliance",
    "polishLastTrainedd266": "Last trained",
    "polishLastSeen5646": "Last seen",
    "polishQuickActionse47e": "Quick actions",
    "polishViewTrainingCalendarf779": "View training calendar",
    "polishAccountProfile765a": "Account & profile"
  },
  "zh": {
    "polishRoundsceea": "轮数",
    "polishTimeCapMin4422": "限时（分钟）",
    "polishTotalMindfea": "总时长（分钟）",
    "polishAllCategories060b": "全部分类",
    "polishDigitalProgramsf261": "数字训练计划",
    "polishBundles9a03": "组合套餐",
    "polishAddOns41b6": "附加项目",
    "polishOnlineCoaching7105": "线上指导",
    "polishInPersonTraining014b": "线下训练",
    "polishInternalGeneralffaa": "内部／通用",
    "polishTitle768e": "名称",
    "polishLevel7c7f": "水平",
    "polishFocusfe7f": "重点",
    "polishType3deb": "类型",
    "polishCreatedBy43de": "创建人",
    "polishActionsc3cd": "操作",
    "polishLoading33ce": "加载中…",
    "polishBuilderQuickNavigationac07": "训练编辑器快捷导航",
    "polishWeekc0ee": "周",
    "polishGoal9fe0": "目标",
    "polishEGBuildMuscle8d3c": "例如：增加肌肉",
    "polishDuration1370": "时长",
    "polishPhasef637": "阶段",
    "polishEGFoundation9fd3": "例如：基础阶段",
    "polishSport1855": "运动项目",
    "polishEGClimbingc373": "例如：攀岩",
    "polishBeginner6057": "初级",
    "polishIntermediateb1cf": "中级",
    "polishAdvanced4d06": "高级",
    "polishElite6f28": "精英",
    "polishProgramType7dbe": "计划类型",
    "polishAssignTocc79": "适用对象",
    "polishInternalGenerala16d": "内部（通用）",
    "polishClient1bdd": "学员",
    "polishTeam2188": "团队",
    "polishSelectClient0765": "选择学员…",
    "polishSelectTeam5c98": "选择团队…",
    "polishDay987b": "天",
    "polishWeekf82b": "周",
    "polishDa3aa": "天 ·",
    "polishSets23fe": "组 ·",
    "polishExe066": "个动作",
    "polishDuplicate972d": "复制",
    "polishUnsaved2ab0": "尚未保存",
    "polishEditSessionaca3": "编辑课次",
    "polishDuplicateToNextWeek8423": "复制到下一周",
    "polishRemoveSessiona72e": "移除课次",
    "polishPhysicalTestdc27": "体能测试",
    "polishNoExercisesYet71ff": "尚未添加动作",
    "polishAdd61cc": "添加",
    "polishCurrentSessionWeek39df": "当前课次 · 周",
    "polishDay2ad3": "· 天",
    "polishCloseEditor3ada": "关闭编辑器",
    "polishAlsoSaveToSessionLibraryb1b8": "同时保存到课次库",
    "polishWorkoutName7adc": "训练名称",
    "polishSessionNamec78b": "课次名称",
    "polishSessionName650a": "课次名称（中文）",
    "polishEstDurationMinfd26": "预计时长（分钟）",
    "polishSessionType3833": "训练类型",
    "polishIntensity0ad6": "强度",
    "polishLowa124": "低",
    "polishModerateea8b": "中等",
    "polishHighb1a5": "高",
    "polishMaxa95e": "最大",
    "polishRecoveryea92": "恢复",
    "polishSessionGoald948": "课次目标",
    "polishPrimaryFocus319f": "本次训练的主要目标…",
    "polishInsertSavedSessioncc09": "插入已保存的课次",
    "polishFromProgram794d": "选择来源计划…",
    "polishPickASession52ec": "选择课次…",
    "polishAll6a72": "全部",
    "polishSets2ab2": "组数",
    "polishReps7020": "次数",
    "polishRestEG90Secb7e4": "休息，例如90秒",
    "polishApplyToc76e": "应用到",
    "polishDragYourSessionIntoShape137c": "安排本次训练",
    "polishAddExercisesToBuildThisSession07d5": "添加动作，开始编排本次训练。",
    "polishAddExercise3ca5": "＋ 添加动作",
    "polishExercises4dc5": "动作",
    "polishSections7ff5": "训练环节",
    "polishSearchExerciseLibrary09bf": "搜索动作库…",
    "polishFilterByEquipmentc44b": "按器械筛选",
    "polishAllEquipmentf3df": "全部器械",
    "polishCancel77df": "取消",
    "polishCreateExerciseb53a": "创建动作",
    "polishNewToTheLibrarySavedANDAddedToThisSessiona5dc": "新动作将保存到动作库，并加入本次训练",
    "polishLoadingExercisesd973": "正在加载动作…",
    "polishNoExercisesMatchThisSearch1df8": "没有符合搜索条件的动作。",
    "polishExerciseOrderbc78": "动作顺序",
    "polishActiveSection34db": "当前环节：",
    "polishChooseASection87f5": "选择训练环节",
    "polishNewExercisesWillBeAddedUnderTheSelectedSection2263": "新增动作将放入所选环节。",
    "polishCustomSection8a73": "自定义环节",
    "polishReturnToSportFingerboardd854": "例如：重返运动、指力板…",
    "polishUse1d4d": "使用",
    "polishColourf285": "颜色",
    "polishChooseAnExerciseFromTheLeftToAddItToThisSessionb592": "从动作库选择动作，加入本次训练。",
    "polishLinkeda089": "已关联",
    "polishLinkTheseExercisesAsASupersetAlternateSets047c": "将这些动作设为超级组，交替完成各组",
    "polishLinkSuperset7988": "关联为超级组",
    "polishLinkTheseExercisesAsACircuitRoundsOfEveryExerciseBackToBack40f1": "将这些动作设为循环组，每轮依次完成全部动作",
    "polishLinkCircuit4dda": "关联为循环组",
    "polishLabel7434": "编号",
    "polishSetAutomaticallyTheLetterAndColourComeFromTheSectionTheNumberFrom0d68": "编号自动生成：字母和颜色由训练环节决定，数字由动作顺序决定。更换环节即可更改字母和颜色。",
    "polishSectionf2c6": "训练环节",
    "polishAccessory9624": "辅助训练",
    "polishOrder1d75": "顺序",
    "polishCollapseExerciseOrderbfee": "收起动作顺序",
    "polishWorkSets125a": "正式组",
    "polishMinb6c9": "分钟",
    "polishEstDurationdca1": "预计时长",
    "polishTempo8996": "动作节奏",
    "polishRestb79e": "休息",
    "polishEdit5301": "编辑",
    "polishAccessoryFordd2d": "辅助动作对应",
    "polishBuilderType18e9": "编排类型",
    "polishSingleWorkout8b3d": "单次训练",
    "polishMultiDayProgram407f": "多日训练计划",
    "polishOptional0c6c": "选填",
    "polishSessionName9dd6": "课次名称",
    "polishEGLowerStrength497a": "例如：下肢力量",
    "polishNextbc98": "下一步",
    "polishViewProgram2e88": "查看计划 ›",
    "polishDetailsa328": "‹ 详情",
    "polishAddExercisesa4ef": "添加动作",
    "polishAddExercise0ca1": "添加动作",
    "polishLinkAsSupersetf478": "＋ 关联为超级组",
    "polishLinkAsCircuit37b2": "＋ 关联为循环组",
    "polishExerciseOptionsb4ed": "动作选项",
    "polishAdd109b": "＋ 添加",
    "polishArrangecfdd": "调整顺序",
    "polishSelectExercisesc770": "选择动作",
    "polishBackb52b": "返回",
    "polishSearchExercisec4cc": "搜索动作…",
    "polishLoadingExercisesd450": "正在加载动作…",
    "polishNoExercisesMatch16db": "没有匹配的动作。",
    "polishArrangeExercises94f0": "调整动作顺序",
    "polishDonee9b4": "完成",
    "polishSupersetd568": "超级组",
    "polishSelectSavedSessionea91": "选择已保存的课次",
    "polishInsertSessionb53b": "插入课次",
    "polishFromProgram22b1": "来源计划",
    "polishChooseAProgram45d8": "选择计划…",
    "polishLoadingSessions3164": "正在加载课次…",
    "polishNoSessionsInThisProgramf4b6": "此计划尚无课次。",
    "polishExercises0ee6": "个动作",
    "polishChange64fb": "更换",
    "polishViewExercise6a3d": "查看动作",
    "polishDeletef6fd": "删除",
    "polishFullSetDetailLoad1RMTempoResta800": "完整组设置：负重、1RM百分比、动作节奏和休息",
    "polishAlternates90d6": "替代动作 ·",
    "polishSwapsTheAthleteCanUseInsteadOfThisExercisee604": "学员可以用以下动作替代本动作。",
    "polishNoAlternatesYetc3dc": "尚未设置替代动作。",
    "polishMoveUpb4f5": "上移",
    "polishMoveDown260f": "下移",
    "polishSearchToAddAnAlternate2546": "搜索并添加替代动作…",
    "polishNoMatches0be6": "没有匹配结果。",
    "polishAllForms04f4": "全部表单",
    "polishSearchForms9253": "搜索表单…",
    "polishItems44d2": "项目数",
    "polishNoSavedFormsYetCreateOneToAssignToClients2172": "尚无已保存的表单。创建表单后即可分配给学员。",
    "polishNoFormsMatchYourSearch3ae9": "没有符合搜索条件的表单。",
    "polishQuestionsff3d": "个问题",
    "polishDuplicateForm4a5d": "复制表单",
    "polishDeleteForme51f": "删除表单",
    "polishForms4bec": "表单",
    "polishFormQuestionnaireBuilder9b72": "表单与问卷编辑器",
    "polishBuildCheckInsIntakeFormsReadinessSurveysAndCustomQuestionnairesFo1d31": "创建打卡表、入组信息表、训练状态调查或自定义问卷，并分配给学员。",
    "polishSavedForms370a": "已保存的表单",
    "polishReloadcce7": "重新加载",
    "polishLoadingFormsc68a": "正在加载表单…",
    "polishNoSavedFormsYet6be8": "尚无已保存的表单。",
    "polishTemplateActionsa931": "模板操作",
    "polishFormName3baf": "表单名称",
    "polishCheckIn4843": "打卡",
    "polishQuestionnaire42d2": "问卷",
    "polishIntaked9e7": "入组信息",
    "polishReadiness6dc1": "训练状态",
    "polishCustom081a": "自定义",
    "polishQuestions9a1f": "问题",
    "polishAddQuestion1475": "＋ 添加问题",
    "polishQuestion002f": "问题",
    "polishQuestionTextdda9": "问题内容",
    "polishTextc332": "简答",
    "polishLongText3afc": "长文本",
    "polishNumberb7ba": "数值",
    "polishScalea29f": "评分量表",
    "polishSingleSelectc17b": "单选",
    "polishMultiSelect9ffa": "多选",
    "polishYesNo9f62": "是／否",
    "polishDateeb9a": "日期",
    "polishRequiredeed6": "必填",
    "polishRemovee963": "移除",
    "polishReviewe29a": "待处理",
    "polishClientCommentsFormTestSubmissionsMissedTasksAndOrderFollowUpsThat49cd": "查看需要教练处理的学员留言、表单及测试结果、未完成任务和订单跟进。",
    "polishNeedsADecision83ce": "待处理事项",
    "polishOpenItemsAcross7QueuesWaitingOnYou9df6": "项待处理事项",
    "polishNoUnansweredMessagesb36c": "没有待回复的消息。👍",
    "polishReplyToYourAthlete7e23": "回复学员…",
    "polishSendReplyMarkReviewed51d8": "发送回复并标记已处理",
    "polishNoCheckInsWaitingForAReply7351": "没有待回复的打卡。",
    "polishReviewReply05e1": "查看并回复 →",
    "polishOpencf9b": "打开",
    "polishArchive2621": "归档",
    "polishWorkoutCommentc988": "训练留言",
    "polishOpenClient9da0": "查看学员",
    "polishNoCommentsOrOrderReviewsWaitingb922": "没有待处理的留言或订单。",
    "polishOnThisPagee1fc": "（本页）",
    "polishMissedWorkout3195": "未完成的训练",
    "polishNoMissedWorkoutsNeedAttention56df": "没有需要跟进的未完成训练。",
    "polishSearchSubmissions849c": "搜索提交记录",
    "polishSearchAthleteOrAssessmentd6e1": "搜索学员或评估…",
    "polishSubmissionStatus6698": "提交状态",
    "polishNeedsReview33a5": "待查看",
    "polishReviewed31ef": "已查看",
    "polishAllSubmissions4ff2": "全部提交",
    "polishNoMatchingFormOrTestSubmissionsc32c": "没有匹配的表单或测试记录。",
    "polishDailyCheckIn35af": "每日打卡",
    "polishSubmitted2e00": "已提交",
    "polishCloseCheckInReview4d6d": "关闭打卡详情",
    "polishYourReplybf9a": "你的回复",
    "polishUpcomingWorkouts1a28": "即将进行的训练",
    "polishDayd420": "· 天",
    "polishChooseDatee787": "选择日期",
    "polishAssignTaska96a": "分配任务",
    "polishProgram9d68": "训练计划",
    "polishStartDate9d7a": "开始日期",
    "polishArrangeWorkouts4458": "安排训练",
    "polishPastedb24": "粘贴",
    "polishAddProgramOrSession623a": "添加计划或课次",
    "polishOpenAssignment82fa": "查看已分配任务",
    "polishDragToAnotherDateOrTapToOpen968d": "拖动到其他日期，或点击查看",
    "polishPreviousMonth46a2": "上个月",
    "polishNextMonth8abf": "下个月",
    "polishAddItemToThisDateae8d": "在此日期添加任务",
    "polishClosebbfa": "关闭",
    "polishSelect8598": "选择",
    "polishNoSessionsYet9d77": "暂无训练记录",
    "polishAthleteSCalendarc77c": "学员训练日历",
    "polishCopyPortalLink8847": "复制学员入口链接",
    "polishRostere551": "学员列表",
    "polishClients28e2": "学员",
    "polishYourAthletesAtAGlanceEngagementAttentionFlagsAndQuickActions01af": "查看学员训练情况、待跟进事项及常用操作。",
    "polishAddClient4b57": "添加学员",
    "polishActiveAthletes78e2": "活跃学员",
    "polishTrainingWithYouNow24ed": "正在接受指导",
    "polishOnline2dbc": "线上",
    "polishInPerson2883": "线下",
    "polishTeams4629": "团队",
    "polishNeedAttention46d0": "需跟进",
    "polishAthletesFlagged3386": "位学员需跟进",
    "polishAverageComplianceThisWeekee2a": "本周平均训练完成率。",
    "polishClientStatusFiltersae1f": "按学员状态筛选",
    "polishSearchClientsb50b": "搜索学员",
    "polishSearchClient11f1": "搜索学员…",
    "polishGroupClientsc8ff": "学员分组",
    "polishNoGroupinga0d0": "不分组",
    "polishOnlinec3e8": "线上",
    "polishInPersone1d7": "线下",
    "polishFilterClientStatusc123": "筛选学员状态",
    "polishAllStatuses6405": "全部状态",
    "polishFilterByCoach589a": "按教练筛选",
    "polishAllCoaches4f5b": "全部教练",
    "polishRefresh56e3": "刷新",
    "polishAttentionFilters00f6": "跟进事项筛选",
    "polishNeedsAttentiona126": "需跟进",
    "polishShowAll50a2": "显示全部",
    "polishSelected835f": "项已选",
    "polishAssignProgram52dc": "分配计划",
    "polishAddToTeamb445": "加入团队",
    "polishAddTage0db": "添加标签",
    "polishCopyLinksd68a": "复制链接",
    "polishClear719e": "清除",
    "polishSelectProgramb398": "选择计划…",
    "polishTagNamefcf2": "标签名称",
    "polishLoadingClients527e": "正在加载学员…",
    "polishNoClientsMatch7494": "没有匹配的学员",
    "polishTryADifferentBucketFilterOrSearch71dd": "请调整分组、筛选条件或搜索内容。",
    "polishAthleteaa86": "学员",
    "polishEngagement4b1f": "训练活跃度",
    "polishAttention74e0": "需跟进事项",
    "polishOpenClientHome238c": "打开学员主页",
    "polishThisWeek7b72": "本周",
    "polishCompliance68f0": "训练完成率",
    "polishLastTrainedd266": "最近训练",
    "polishLastSeen5646": "最近访问",
    "polishQuickActionse47e": "快捷操作",
    "polishViewTrainingCalendarf779": "查看训练日历",
    "polishAccountProfile765a": "账户与资料"
  }
};
