export const redesignCopy = {
  en: {
    athleteMarkRead: "Mark all read",
    redesignDays_one: "{{count}} day", redesignDays_other: "{{count}} days", redesignExercises_one: "{{count}} exercise", redesignExercises_other: "{{count}} exercises", redesignSets_one: "{{count}} set", redesignSets_other: "{{count}} sets",
    athleteToday: "Today", athleteTraining: "Training", athleteMe: "Me", athleteCoach: "Coach", athleteSupport: "Support", athleteGetStarted: "Get started",
    athleteGreeting: "Hi, {{name}}", athleteTodayTraining: "Today's training", athleteRest: "Rest day", athleteNext: "Next session", athleteAllDone: "Today's training is complete", athleteNoPlan: "No upcoming training", athleteHabits: "Daily habits", athleteWellness: "Daily check-in", athleteLoad: "Training load", athleteProgress: "Training progress", athleteCompleted: "{{done}} / {{total}} sessions completed", athleteViewTraining: "View training", athleteMyTraining: "My training", athleteNumbers: "Training numbers", athleteHistory: "Exercise history & records", athleteAssessments: "Assessments & questionnaires", athletePrograms: "My programs", athleteAccount: "Account & settings", athleteFeedback: "Feedback & updates", athleteMessages: "Messages", athleteMessageHint: "Send a training question or update. Your replies appear here.", athleteMessageBody: "Your message", athleteSend: "Send message", athleteSent: "Message sent", athleteSendFailed: "Couldn't send. Your message is kept here; please retry.", athleteLoadFailed: "Couldn't load this information. Please retry.", athleteRetry: "Retry", athleteNoMessages: "No messages yet", athleteNoFeedback: "No feedback yet", athleteReply: "Reply", athletePreviewNotice: "Preview is read only. Submissions are disabled.", athleteNoAssessments: "No assessments assigned", athleteBackMe: "Back to Me", athleteBackToday: "Back to Today", athleteCoachContact: "Contact your coach", athleteSupportContact: "Contact support", athleteScanQr: "Scan with WeChat", athleteNoContact: "Use Messages to ask a question or request contact details.", athletePreviewPhone: "Phone preview", athletePreviewWide: "Expand preview", athleteExerciseDetails: "Exercise details",
    redesignSessionNotes: "Session notes", redesignNotesHint: "Session instructions and warm-up guidance", redesignDetails: "Details", redesignWeek: "Week {{week}}", redesignAddDay: "Add day", redesignCopyDay: "Copy to next week", redesignDuplicateWeek: "Duplicate week", redesignDays: "{{count}} days", redesignExercises: "{{count}} exercises", redesignSets: "{{count}} sets", redesignSelect: "Select", redesignDone: "Done", redesignSession: "Saved workout", redesignProgram: "Program", redesignTest: "Test", redesignNewWorkout: "New workout", redesignAddToDate: "Add to {{date}}", redesignSaveProgram: "Save program", redesignUpdateProgram: "Update program", redesignSaving: "Saving…", redesignReviewProgram: "Review program", redesignWeekView: "Week", redesignMonthView: "Month", redesignFullView: "Full", redesignDayDraft: "Day draft · save the program to publish", redesignRecent: "Recently used", redesignReps: "{{value}} reps",
  },
  zh: {
    athleteMarkRead: "全部标为已读",
    redesignDays_one: "{{count}} 个训练日", redesignExercises_one: "{{count}} 个动作", redesignSets_one: "{{count}} 组",
    redesignDays_other: "{{count}} 个训练日", redesignExercises_other: "{{count}} 个动作", redesignSets_other: "{{count}} 组",
    athleteToday: "今日", athleteTraining: "训练", athleteMe: "我的", athleteCoach: "教练", athleteSupport: "支持", athleteGetStarted: "了解训练",
    athleteGreeting: "你好，{{name}}", athleteTodayTraining: "今日训练", athleteRest: "休息日", athleteNext: "下次训练", athleteAllDone: "今日训练已完成", athleteNoPlan: "暂无后续训练安排", athleteHabits: "每日习惯", athleteWellness: "状态打卡", athleteLoad: "训练负荷", athleteProgress: "训练进度", athleteCompleted: "已完成 {{done}} / {{total}} 次训练", athleteViewTraining: "查看训练", athleteMyTraining: "我的训练", athleteNumbers: "训练数据", athleteHistory: "动作历史与个人记录", athleteAssessments: "测试与问卷", athletePrograms: "我的训练计划", athleteAccount: "账户与设置", athleteFeedback: "反馈与动态", athleteMessages: "留言", athleteMessageHint: "发送训练问题或近况，在这里查看回复。", athleteMessageBody: "留言内容", athleteSend: "发送留言", athleteSent: "留言已发送", athleteSendFailed: "发送失败，内容已保留，请重试。", athleteLoadFailed: "暂时无法加载，请重试。", athleteRetry: "重试", athleteNoMessages: "暂无留言", athleteNoFeedback: "暂无反馈", athleteReply: "回复", athletePreviewNotice: "当前为只读预览，无法提交。", athleteNoAssessments: "暂无测试或问卷", athleteBackMe: "返回我的", athleteBackToday: "返回今日", athleteCoachContact: "联系教练", athleteSupportContact: "联系支持", athleteScanQr: "使用微信扫码", athleteNoContact: "可通过留言咨询问题或获取联系方式。", athletePreviewPhone: "手机预览", athletePreviewWide: "展开预览", athleteExerciseDetails: "动作详情",
    redesignSessionNotes: "训练备注", redesignNotesHint: "本次训练说明与热身提示", redesignDetails: "详细设置", redesignWeek: "第 {{week}} 周", redesignAddDay: "添加训练日", redesignCopyDay: "复制到下一周", redesignDuplicateWeek: "复制本周", redesignDays: "{{count}} 个训练日", redesignExercises: "{{count}} 个动作", redesignSets: "{{count}} 组", redesignSelect: "选择", redesignDone: "完成", redesignSession: "已保存训练", redesignProgram: "训练计划", redesignTest: "体能测试", redesignNewWorkout: "新建训练", redesignAddToDate: "添加到 {{date}}", redesignSaveProgram: "保存计划", redesignUpdateProgram: "更新计划", redesignSaving: "保存中…", redesignReviewProgram: "查看计划", redesignWeekView: "周", redesignMonthView: "月", redesignFullView: "全部", redesignDayDraft: "训练日草稿 · 保存计划后发布", redesignRecent: "最近使用", redesignReps: "{{value}} 次",
  },
};
