import type {
  CompanyOpsLanguage,
  CompanyOpsRole,
  QuickActionKey,
} from "./types";

const en = {
  appName: "Company Operations",
  appSubtitle: "Your work, decisions and company records in one place.",
  navHome: "Home",
  navPerformance: "Performance",
  navGrowth: "Growth",
  navCalendar: "Calendar",
  navArticles: "Articles",
  navDecisions: "Decisions",
  navOnboarding: "Onboarding",
  navPolicies: "Policies",
  refresh: "Refresh",
  refreshing: "Refreshing…",
  signOut: "Sign out",
  switchToChinese: "中文",
  switchToEnglish: "EN",
  founderRole: "Founder",
  growthRole: "Brand & Growth",
  financeRole: "Finance",
  employeeRole: "Team member",
  welcome: "Hello, {{name}}",
  welcomeSub: "Here is what needs your attention today.",
  loginTitle: "Open Company Operations",
  loginBody:
    "Sign in with your company Feishu account. Your role determines what you can see and do.",
  continueWithFeishu: "Continue with Feishu",
  loginPrivacy: "Payroll, identity and bank information remain restricted. Cross-language text may be machine-translated by an approved AI service.",
  loadingTitle: "Preparing your workspace",
  loadingBody: "Loading the work and decisions relevant to your role…",
  loadErrorTitle: "We could not load Company Operations",
  loadErrorBody: "Your data was not changed. Check your connection and try again.",
  retry: "Try again",
  noAccessTitle: "This account does not have access",
  noAccessBody:
    "Send an access request here. A founder will review it and assign the correct role.",
  requestAccess: "Request access",
  requestingAccess: "Sending request…",
  accessRequestSent: "Your request is waiting for founder review.",
  todayFocus: "Your next priority",
  quietFocusTitle: "You are clear for now",
  quietFocusBody: "No urgent work is waiting. Use a quick action to keep the week moving.",
  quickActions: "Quick actions",
  quickActionsHint: "Start the common workflows without opening a Base.",
  myWork: "My work",
  myWorkHint: "Only items that need an owner or a next action appear here.",
  noWorkTitle: "Nothing needs action",
  noWorkBody: "New assigned work and follow-ups will appear here.",
  weeklyRhythm: "This part of the week",
  weekChecklist: "Recommended focus",
  companyResources: "Company resources",
  policiesAndGuides: "Policies & guides",
  policiesHint: "Read-only company guidance and approved operating procedures.",
  policyLibraryTitle: "Company policies & playbooks",
  policyLibraryIntro:
    "Find the current approved guidance without searching through chats or folders.",
  policyRequired: "Required",
  openResource: "Open",
  advancedRecords: "Advanced records",
  advancedRecordsHint: "Open the underlying Base only when detailed record work is needed.",
  openItem: "Open item",
  dueToday: "Due today",
  overdue: "Overdue",
  dueSoon: "Due soon",
  owner: "Owner",
  status: "Status",
  close: "Close",
  cancel: "Cancel",
  submit: "Submit",
  saving: "Saving…",
  saved: "Saved",
  actionFailed: "That action could not be saved. Please try again.",
  actionSuccess: "Saved. The relevant people can see it now.",
  contentAction: "Create content idea",
  leadAction: "Capture a lead",
  partnerAction: "Add a partner",
  campaignAction: "Create a campaign",
  experimentAction: "Create an experiment",
  platformMetricsAction: "Record platform metrics",
  supportIssueAction: "Report a product issue",
  onboardingSetupAction: "Start employee onboarding",
  reportAction: "Submit weekly report",
  expenseAction: "Submit an expense",
  decisionAction: "Request a decision",
  internalRequestAction: "Request something",
  contentHookField: "Hook / opening line (optional)",
  contentCopyField: "Copy / caption draft (optional)",
  contentKeywordsField: "SEO keywords (optional)",
  contentHashtagsField: "Hashtags (optional)",
  contentCtaField: "Call to action (optional)",
  contentIdeaNotesField: "Idea notes & references (optional)",
  keyDatesTitle: "Dates that bite",
  keyDatesHint: "Licences, probation reviews, renewals — surfaced before they hurt.",
  keyDatesEmpty: "Nothing urgent in the next 60 days.",
  goalAction: "Share a goal or idea",
  goalsTitle: "Company goals & founder ideas",
  goalsHint: "Direction from the founders — respond so they know it landed.",
  noGoalsTitle: "No goals shared yet",
  noGoalsBody: "Goals and founder ideas will appear here for the whole team.",
  goalFrom: "From {{name}}",
  goalRespondPlaceholder: "Respond to this goal or idea…",
  goalRespondSend: "Send response",
  goalFormTitle: "Share a goal or idea",
  goalFormIntro: "The team sees it on their home page and can respond.",
  goalTitleField: "Goal or idea",
  goalTypeField: "Type",
  goalMeasureField: "How we'll measure it",
  goalPriorityField: "Priority",
  goalDueField: "Due",
  requestTitle: "What do you need?",
  requestCategory: "Category",
  requestDetails: "Details",
  requestNeededBy: "Needed by",
  categoryFinance: "Finance",
  categoryPeople: "People",
  decisionFeedback: "Feedback (optional)",
  decisionFeedbackPlaceholder: "Write feedback to send with your decision…",
  openReceipt: "Open receipt",
  myExpensesTitle: "My submissions",
  myExpensesHint: "Your expense claims and where they stand.",
  payBase: "Base salary",
  payPerformanceBonus: "Performance bonus",
  payReimbursements: "Reimbursements",
  payDeductions: "Deductions",
  payNet: "Net pay",
  moveStatus: "Move to…",
  myPay: "My pay",
  privatePayHint: "Private to you and authorized finance staff.",
  payPeriod: "Pay period",
  payrollStatus: "Payroll status",
  commissionAmount: "Commission amount",
  commissionStatus: "Commission status",
  disputeDeadline: "Question deadline",
  acknowledgePay: "Acknowledge",
  disputePay: "Raise a question",
  payAcknowledged: "Acknowledged",
  payLocked: "This pay period is closed.",
  growthEyebrow: "Brand & Growth workspace",
  growthTitle: "Growth command center",
  growthIntro:
    "Plan, publish, follow up and learn—without losing work in private chats.",
  thisWeekPulse: "This week at a glance",
  contentPipeline: "Content pipeline",
  contentPipelineHint: "The detailed 12-status workflow, grouped into five clear phases.",
  noContentTitle: "No content in this phase",
  noContentBody: "Move work forward or create the first idea.",
  nextToPublish: "Next to publish",
  noUpcomingContent: "Nothing is scheduled yet.",
  followUps: "Follow-ups",
  leads: "Leads",
  partners: "Partners",
  noLeadFollowUps: "No lead follow-ups are due.",
  noPartnerFollowUps: "No partner follow-ups are due.",
  nextAction: "Next action",
  nextFollowUp: "Next follow-up",
  activeCampaigns: "Active campaigns",
  noActiveCampaigns: "No active campaign is currently recorded.",
  experiments: "Growth experiments",
  noExperiments: "No experiment is running. Record a hypothesis before testing.",
  weeklyReportDue: "Friday report is due",
  weeklyReportReady: "Weekly report submitted",
  founderEyebrow: "Founder workspace",
  founderTitle: "Decision inbox",
  founderIntro:
    "Approve exceptions and unblock the team. Routine work stays with its owner.",
  decisionCount: "{{count}} open decisions",
  noDecisionsTitle: "The team is unblocked",
  noDecisionsBody: "New approval and founder-decision requests will appear here.",
  requestedBy: "Requested by",
  approve: "Approve",
  requestChanges: "Request changes",
  viewContext: "View context",
  restrictedFinance: "Restricted finance overview",
  financeHint: "Visible only to founders and authorized finance staff.",
  payroll: "Payroll",
  commissions: "Commissions",
  expenses: "Expenses",
  onboardingWatch: "Onboarding watch",
  noOnboardingBlockers: "No onboarding blocker needs founder action.",
  growthPulse: "Growth pulse",
  onboardingEyebrow: "Employee onboarding",
  onboardingTitle: "Your onboarding journey",
  onboardingIntro:
    "Complete one clear step at a time. Confidential details stay in the restricted HR workflow.",
  onboardingProgress: "{{count}}% complete",
  nextOnboardingStep: "Next step",
  allOnboardingDone: "Onboarding complete",
  allOnboardingDoneBody: "You have completed every required onboarding step.",
  confidentialDetails: "Confidential employee details",
  confidentialComplete: "Submitted securely",
  confidentialIncomplete: "Action required",
  confidentialBody:
    "ID, bank and tax details are never displayed in this shared workspace.",
  openSecureForm: "Open secure HR form",
  onboardingTimeline: "Milestones",
  phaseBeforeStart: "Before start",
  phaseWeekOne: "Week 1",
  phaseDay30: "First 30 days",
  phaseDay60: "Days 31–60",
  phaseDay90: "Days 61–90",
  markComplete: "Mark complete",
  completed: "Completed",
  helpContact: "Need help? Contact {{name}}.",
  requiredPolicies: "Required reading",
  acknowledged: "Acknowledged",
  acknowledge: "Acknowledge",
  readPolicy: "Read policy",
  noPolicies: "No policies have been assigned.",
  contentFormTitle: "Create a content idea",
  contentFormIntro: "Capture enough information to make the next action obvious.",
  workingTitle: "Working title",
  platform: "Platform",
  choosePlatform: "Choose a platform",
  xiaohongshu: "Xiaohongshu",
  douyin: "Douyin",
  wechat: "WeChat Official Account",
  multiPlatform: "Multi-platform",
  contentPillar: "Content pillar",
  objective: "Objective",
  plannedPublishDate: "Planned publish date",
  leadFormTitle: "Capture a lead",
  leadFormIntro: "Record the commercial follow-up—not health or injury information.",
  leadName: "Name",
  contact: "WeChat / contact",
  source: "Lead source",
  productInterest: "Product interest",
  leadNextAction: "Next action",
  noHealthData: "Do not enter medical, injury or detailed coaching information here.",
  partnerFormTitle: "Add a partner",
  partnerFormIntro: "Record the fit, relationship and next follow-up.",
  partnerName: "Partner / creator name",
  handle: "Handle",
  audienceFit: "Audience fit",
  proposedCollaboration: "Proposed collaboration",
  followUpDate: "Next follow-up date",
  campaignFormTitle: "Create a campaign",
  campaignFormIntro: "Set the commercial goal, offer, channels, budget and dates before work begins.",
  campaignName: "Campaign name",
  targetAudience: "Target audience",
  offer: "Offer",
  product: "Product",
  channels: "Channels",
  budget: "Budget",
  startDate: "Start date",
  endDate: "End date",
  experimentFormTitle: "Create a growth experiment",
  experimentFormIntro: "Record one testable hypothesis and the result that will determine the decision.",
  experimentName: "Experiment name",
  hypothesis: "Hypothesis",
  variable: "Variable being tested",
  channel: "Channel",
  successMetric: "Success metric",
  baseline: "Baseline",
  target: "Target",
  metricsFormTitle: "Record platform metrics",
  metricsFormIntro: "Capture a consistent period snapshot so trends and learnings stay comparable.",
  period: "Reporting period",
  startFollowers: "Starting followers",
  endFollowers: "Ending followers",
  posts: "Posts published",
  views: "Views",
  engagement: "Engagement",
  profileVisits: "Profile visits",
  clicks: "Clicks",
  revenue: "Revenue",
  learning: "Key learning",
  supportFormTitle: "Report a product or app issue",
  supportFormIntro: "Give the product team a clear, reproducible issue without sharing passwords or sensitive customer data.",
  onboardingFormTitle: "Start employee onboarding",
  onboardingFormIntro:
    "Choose the employee, role and start date. The approved checklist will be assigned automatically without duplicate tasks.",
  newHire: "Employee",
  newHireName: "Employee name",
  feishuOpenId: "Feishu Open ID",
  onboardingRole: "Onboarding role",
  employmentStartDate: "Start date",
  issueTitle: "Issue title",
  severity: "Severity",
  issueType: "Issue type",
  feature: "Feature / area",
  deviceOs: "Device and OS",
  issueDescription: "What happened",
  reproductionSteps: "Steps to reproduce",
  affectedCount: "People affected",
  workaround: "Known workaround",
  disputeFormTitle: "Raise a pay question",
  disputeFormIntro: "Explain the specific payroll or commission item that finance should review.",
  disputeReason: "Question and supporting context",
  reportFormTitle: "Weekly founder report",
  reportFormIntro: "A concise A–F review that ends with clear decisions and priorities.",
  reportingWeek: "Reporting week",
  reportCompleted: "A. Completed",
  reportResults: "B. Results",
  reportProblems: "C. Problems",
  reportLearnings: "D. Learnings",
  reportDecisions: "E. Decisions needed",
  reportNextWeek: "F. Next week",
  expenseFormTitle: "Submit an expense",
  expenseFormIntro: "Include the business purpose and approval reference where required.",
  expenseCategory: "Category",
  amount: "Amount",
  currency: "Currency",
  expenseDate: "Expense date",
  businessPurpose: "Business purpose",
  relatedProject: "Campaign / project",
  preapproved: "Pre-approved",
  priorApprovalReference: "Approval reference",
  receiptNote: "Receipt / fapiao note",
  receiptUrl: "Receipt or fapiao link",
  receiptUrlHint:
    "Paste a secure HTTPS link to the receipt. If you need to upload a file, use the Feishu expense form from the quick action instead.",
  decisionFormTitle: "Request a founder decision",
  requestFormTitle: "Internal request",
  requestFormIntro: "Ask for equipment, access, purchases or anything the company should handle.",
  decisionFormIntro: "Ask one clear question and explain what is blocked.",
  decisionTitle: "Decision needed",
  decisionCategory: "Category",
  decisionContext: "Context and recommendation",
  neededBy: "Needed by",
  categoryContent: "Content / claims",
  categorySpend: "Spend / budget",
  categoryPartner: "Partner terms",
  categoryFilming: "Founder filming",
  categoryPricing: "Pricing / offer",
  categoryOther: "Other",
  requiredField: "Please complete this field.",
  selectOne: "Select one",
  openInFeishu: "Open in Feishu",
  generatedAt: "Updated {{time}}",
} as const;

type CopyKey = keyof typeof en;

const zh: Record<CopyKey, string> = {
  appName: "公司运营中心",
  appSubtitle: "工作、审批与公司记录，一处完成。",
  navHome: "首页",
  navPerformance: "月度绩效",
  navGrowth: "增长",
  navCalendar: "内容日历",
  navArticles: "文章创作",
  navDecisions: "待决策",
  navOnboarding: "入职",
  navPolicies: "制度",
  refresh: "刷新",
  refreshing: "正在刷新…",
  signOut: "退出登录",
  switchToChinese: "中文",
  switchToEnglish: "EN",
  founderRole: "创始人",
  growthRole: "品牌与增长",
  financeRole: "财务",
  employeeRole: "团队成员",
  welcome: "{{name}}，你好",
  welcomeSub: "以下是今天需要你关注的事项。",
  loginTitle: "进入公司运营中心",
  loginBody: "请使用公司飞书账号登录。系统会根据你的岗位显示相应内容与操作。",
  continueWithFeishu: "使用飞书继续",
  loginPrivacy: "工资、身份信息与银行资料始终限制访问。跨语言内容可能由公司批准的AI服务自动翻译。",
  loadingTitle: "正在准备你的工作台",
  loadingBody: "正在加载与你岗位相关的工作与待决策事项…",
  loadErrorTitle: "暂时无法加载公司运营中心",
  loadErrorBody: "你的数据没有发生变化。请检查网络后重试。",
  retry: "重试",
  noAccessTitle: "此账号暂无访问权限",
  noAccessBody: "请在这里提交访问申请。创始人审核后会分配正确的岗位权限。",
  requestAccess: "申请访问权限",
  requestingAccess: "正在提交…",
  accessRequestSent: "申请已提交，正在等待创始人审核。",
  todayFocus: "下一项优先工作",
  quietFocusTitle: "目前没有紧急事项",
  quietFocusBody: "你可以通过快捷操作继续推进本周工作。",
  quickActions: "快捷操作",
  quickActionsHint: "无需打开多维表格，直接发起常用流程。",
  myWork: "我的工作",
  myWorkHint: "这里只显示需要负责人或下一步行动的事项。",
  noWorkTitle: "暂无待办事项",
  noWorkBody: "新分配的工作与跟进事项会显示在这里。",
  weeklyRhythm: "本周当前节奏",
  weekChecklist: "建议重点",
  companyResources: "公司资源",
  policiesAndGuides: "制度与指南",
  policiesHint: "只读的公司制度与已批准操作流程。",
  policyLibraryTitle: "公司制度与工作指南",
  policyLibraryIntro: "无需翻找聊天或文件夹，即可查看当前已批准的最新指引。",
  policyRequired: "必读",
  openResource: "打开",
  advancedRecords: "详细记录",
  advancedRecordsHint: "只有需要处理完整记录时，才打开底层多维表格。",
  openItem: "打开事项",
  dueToday: "今天到期",
  overdue: "已逾期",
  dueSoon: "即将到期",
  owner: "负责人",
  status: "状态",
  close: "关闭",
  cancel: "取消",
  submit: "提交",
  saving: "正在保存…",
  saved: "已保存",
  actionFailed: "保存失败，请重试。",
  actionSuccess: "已保存，相关人员现在可以查看。",
  contentAction: "创建内容创意",
  leadAction: "录入销售线索",
  partnerAction: "添加合作伙伴",
  campaignAction: "创建营销活动",
  experimentAction: "创建增长实验",
  platformMetricsAction: "记录平台数据",
  supportIssueAction: "报告产品问题",
  onboardingSetupAction: "启动员工入职",
  reportAction: "提交周报",
  expenseAction: "提交报销",
  decisionAction: "请求决策",
  internalRequestAction: "提交内部请求",
  contentHookField: "钩子/开头（选填）",
  contentCopyField: "文案草稿（选填）",
  contentKeywordsField: "SEO关键词（选填）",
  contentHashtagsField: "话题标签（选填）",
  contentCtaField: "行动号召（选填）",
  contentIdeaNotesField: "创意备注/参考（选填）",
  keyDatesTitle: "重要日期",
  keyDatesHint: "证照、试用期评估、续费——在出问题之前提醒你。",
  keyDatesEmpty: "未来60天没有紧急事项。",
  goalAction: "发布目标/想法",
  goalsTitle: "公司目标与创始人想法",
  goalsHint: "来自创始人的方向——回应一下，让他们知道你看到了。",
  noGoalsTitle: "暂无目标",
  noGoalsBody: "公司目标和创始人想法会显示在这里，全员可见。",
  goalFrom: "来自 {{name}}",
  goalRespondPlaceholder: "回应这个目标或想法…",
  goalRespondSend: "发送回应",
  goalFormTitle: "发布目标或想法",
  goalFormIntro: "团队会在首页看到，并可以直接回应。",
  goalTitleField: "目标或想法",
  goalTypeField: "类型",
  goalMeasureField: "衡量标准",
  goalPriorityField: "优先级",
  goalDueField: "截止时间",
  requestTitle: "你需要什么？",
  requestCategory: "类别",
  requestDetails: "详情",
  requestNeededBy: "期望完成时间",
  categoryFinance: "财务",
  categoryPeople: "人事",
  decisionFeedback: "反馈（可选）",
  decisionFeedbackPlaceholder: "写下随决定一起发送的反馈…",
  openReceipt: "查看票据",
  myExpensesTitle: "我的报销",
  myExpensesHint: "你提交的报销及当前进度。",
  payBase: "基本工资",
  payPerformanceBonus: "绩效奖金",
  payReimbursements: "报销",
  payDeductions: "扣款",
  payNet: "实发",
  moveStatus: "移动到…",
  myPay: "我的薪酬",
  privatePayHint: "仅你本人及获授权的财务人员可见。",
  payPeriod: "薪酬周期",
  payrollStatus: "工资状态",
  commissionAmount: "提成金额",
  commissionStatus: "提成状态",
  disputeDeadline: "疑问提交截止日",
  acknowledgePay: "确认无误",
  disputePay: "提出疑问",
  payAcknowledged: "已确认",
  payLocked: "本薪酬周期已关闭。",
  growthEyebrow: "品牌与增长工作台",
  growthTitle: "增长指挥中心",
  growthIntro: "从规划、发布到跟进与复盘，避免工作遗失在私人聊天中。",
  thisWeekPulse: "本周概览",
  contentPipeline: "内容流程",
  contentPipelineHint: "保留完整的 12 个状态，并归纳为 5 个清晰阶段。",
  noContentTitle: "此阶段暂无内容",
  noContentBody: "继续推进现有工作，或创建第一个创意。",
  nextToPublish: "即将发布",
  noUpcomingContent: "暂未安排发布内容。",
  followUps: "待跟进",
  leads: "销售线索",
  partners: "合作伙伴",
  noLeadFollowUps: "暂无到期的线索跟进。",
  noPartnerFollowUps: "暂无到期的合作伙伴跟进。",
  nextAction: "下一步",
  nextFollowUp: "下次跟进",
  activeCampaigns: "进行中的营销活动",
  noActiveCampaigns: "目前没有记录进行中的营销活动。",
  experiments: "增长实验",
  noExperiments: "目前没有进行中的实验。测试前请先记录假设。",
  weeklyReportDue: "本周五周报待提交",
  weeklyReportReady: "本周周报已提交",
  founderEyebrow: "创始人工作台",
  founderTitle: "待决策收件箱",
  founderIntro: "审批例外事项并解除团队阻碍，日常执行仍由对应负责人完成。",
  decisionCount: "{{count}} 项待决策",
  noDecisionsTitle: "团队目前没有阻碍",
  noDecisionsBody: "新的审批与创始人决策请求会显示在这里。",
  requestedBy: "申请人",
  approve: "批准",
  requestChanges: "要求修改",
  viewContext: "查看背景",
  restrictedFinance: "受限财务概览",
  financeHint: "仅创始人与获授权财务人员可见。",
  payroll: "工资",
  commissions: "提成",
  expenses: "报销",
  onboardingWatch: "入职进度",
  noOnboardingBlockers: "目前没有需要创始人处理的入职阻碍。",
  growthPulse: "增长概览",
  onboardingEyebrow: "员工入职",
  onboardingTitle: "你的入职旅程",
  onboardingIntro: "每次完成一个清晰步骤。敏感资料始终进入受限的人事流程。",
  onboardingProgress: "已完成 {{count}}%",
  nextOnboardingStep: "下一步",
  allOnboardingDone: "入职流程已完成",
  allOnboardingDoneBody: "你已完成所有必需的入职步骤。",
  confidentialDetails: "员工保密资料",
  confidentialComplete: "已安全提交",
  confidentialIncomplete: "需要处理",
  confidentialBody: "身份证、银行与税务资料不会显示在这个共享工作台中。",
  openSecureForm: "打开安全人事表单",
  onboardingTimeline: "里程碑",
  phaseBeforeStart: "入职前",
  phaseWeekOne: "第一周",
  phaseDay30: "前 30 天",
  phaseDay60: "第 31–60 天",
  phaseDay90: "第 61–90 天",
  markComplete: "标记完成",
  completed: "已完成",
  helpContact: "需要帮助？请联系 {{name}}。",
  requiredPolicies: "必读制度",
  acknowledged: "已确认",
  acknowledge: "确认已阅读",
  readPolicy: "阅读制度",
  noPolicies: "目前没有分配给你的制度文件。",
  contentFormTitle: "创建内容创意",
  contentFormIntro: "记录足够信息，让下一步行动一目了然。",
  workingTitle: "暂定标题",
  platform: "平台",
  choosePlatform: "请选择平台",
  xiaohongshu: "小红书",
  douyin: "抖音",
  wechat: "微信公众号",
  multiPlatform: "多平台",
  contentPillar: "内容支柱",
  objective: "目标",
  plannedPublishDate: "计划发布日期",
  leadFormTitle: "录入销售线索",
  leadFormIntro: "这里只记录商业跟进，不记录健康或伤病信息。",
  leadName: "姓名",
  contact: "微信／联系方式",
  source: "线索来源",
  productInterest: "感兴趣的产品",
  leadNextAction: "下一步行动",
  noHealthData: "请勿在此输入医疗、伤病或详细训练信息。",
  partnerFormTitle: "添加合作伙伴",
  partnerFormIntro: "记录合作匹配度、关系阶段与下次跟进时间。",
  partnerName: "合作伙伴／创作者名称",
  handle: "账号名称",
  audienceFit: "受众匹配度",
  proposedCollaboration: "建议合作方式",
  followUpDate: "下次跟进日期",
  campaignFormTitle: "创建营销活动",
  campaignFormIntro: "开始执行前，先明确商业目标、优惠、渠道、预算与日期。",
  campaignName: "活动名称",
  targetAudience: "目标受众",
  offer: "优惠方案",
  product: "产品",
  channels: "推广渠道",
  budget: "预算",
  startDate: "开始日期",
  endDate: "结束日期",
  experimentFormTitle: "创建增长实验",
  experimentFormIntro: "记录一个可验证的假设，以及用于决定下一步的结果指标。",
  experimentName: "实验名称",
  hypothesis: "实验假设",
  variable: "测试变量",
  channel: "渠道",
  successMetric: "成功指标",
  baseline: "基准值",
  target: "目标值",
  metricsFormTitle: "记录平台数据",
  metricsFormIntro: "按统一周期记录数据，便于持续比较趋势并沉淀经验。",
  period: "统计周期",
  startFollowers: "期初粉丝数",
  endFollowers: "期末粉丝数",
  posts: "发布数量",
  views: "浏览量",
  engagement: "互动量",
  profileVisits: "主页访问量",
  clicks: "点击量",
  revenue: "收入",
  learning: "关键经验",
  supportFormTitle: "报告产品或应用问题",
  supportFormIntro: "请提供清晰、可复现的问题描述，不要填写密码或敏感客户资料。",
  onboardingFormTitle: "启动员工入职",
  onboardingFormIntro: "选择员工、岗位和入职日期。系统会自动分配已批准的清单，并避免重复任务。",
  newHire: "员工",
  newHireName: "员工姓名",
  feishuOpenId: "飞书 Open ID",
  onboardingRole: "入职岗位",
  employmentStartDate: "入职日期",
  issueTitle: "问题标题",
  severity: "严重程度",
  issueType: "问题类型",
  feature: "功能／区域",
  deviceOs: "设备与操作系统",
  issueDescription: "问题现象",
  reproductionSteps: "复现步骤",
  affectedCount: "受影响人数",
  workaround: "临时解决办法",
  disputeFormTitle: "提出薪酬疑问",
  disputeFormIntro: "请说明需要财务核查的具体工资或提成项目。",
  disputeReason: "疑问与相关说明",
  reportFormTitle: "创始人周报",
  reportFormIntro: "用简洁的 A–F 结构总结结果、决策与下周重点。",
  reportingWeek: "报告周",
  reportCompleted: "A. 已完成",
  reportResults: "B. 结果",
  reportProblems: "C. 问题",
  reportLearnings: "D. 经验",
  reportDecisions: "E. 需要决策",
  reportNextWeek: "F. 下周重点",
  expenseFormTitle: "提交报销",
  expenseFormIntro: "请填写业务用途，以及需要时填写事前审批编号。",
  expenseCategory: "费用类别",
  amount: "金额",
  currency: "币种",
  expenseDate: "费用日期",
  businessPurpose: "业务用途",
  relatedProject: "相关活动／项目",
  preapproved: "已事前审批",
  priorApprovalReference: "审批编号",
  receiptNote: "收据／发票说明",
  receiptUrl: "收据或发票链接",
  receiptUrlHint: "请粘贴安全的 HTTPS 票据链接。如需直接上传文件，请从快捷操作打开飞书报销表单。",
  decisionFormTitle: "请求创始人决策",
  requestFormTitle: "内部请求",
  requestFormIntro: "申请设备、权限、采购或任何需要公司处理的事项。",
  decisionFormIntro: "只提出一个清晰问题，并说明当前受阻事项。",
  decisionTitle: "需要的决策",
  decisionCategory: "类别",
  decisionContext: "背景与建议",
  neededBy: "最迟决策日期",
  categoryContent: "内容／宣传表述",
  categorySpend: "费用／预算",
  categoryPartner: "合作条款",
  categoryFilming: "创始人拍摄",
  categoryPricing: "价格／优惠",
  categoryOther: "其他",
  requiredField: "请填写此项。",
  selectOne: "请选择",
  openInFeishu: "在飞书中打开",
  generatedAt: "更新于 {{time}}",
};

export type OpsCopyKey = CopyKey;

export function opsText(
  language: CompanyOpsLanguage,
  key: CopyKey,
  variables: Record<string, string | number> = {},
) {
  let value = (language === "zh" ? zh : en)[key] as string;
  for (const [name, replacement] of Object.entries(variables)) {
    value = value.replaceAll(`{{${name}}}`, String(replacement));
  }
  return value;
}

export function roleLabel(language: CompanyOpsLanguage, role: CompanyOpsRole) {
  const key: CopyKey =
    role === "founder"
      ? "founderRole"
      : role === "growth"
        ? "growthRole"
        : role === "finance"
          ? "financeRole"
          : "employeeRole";
  return opsText(language, key);
}

export function quickActionLabel(
  language: CompanyOpsLanguage,
  action: QuickActionKey,
) {
  const keys: Record<QuickActionKey, CopyKey> = {
    content: "contentAction",
    lead: "leadAction",
    partner: "partnerAction",
    campaign: "campaignAction",
    experiment: "experimentAction",
    platform_metrics: "platformMetricsAction",
    support_issue: "supportIssueAction",
    onboarding_setup: "onboardingSetupAction",
    compensation_dispute: "disputePay",
    weekly_report: "reportAction",
    expense: "expenseAction",
    internal_request: "internalRequestAction",
    goal: "goalAction",
    founder_decision: "decisionAction",
  };
  return opsText(language, keys[action]);
}

// Feishu-sourced statuses reach the client as canonical English names; map
// them to natural Chinese at render time so Yumei's pills aren't English.
// Unknown statuses fall through unchanged.
const STATUS_ZH: Record<string, string> = {
  Pending: "待审批",
  Approved: "已批准",
  Rejected: "已拒绝",
  Reimbursed: "已打款",
  Submitted: "已提交",
  Reviewed: "已阅",
  Open: "待处理",
  "In Progress": "进行中",
  Doing: "进行中",
  Done: "完成",
  Declined: "已拒绝",
  Todo: "未开始",
  Idea: "想法",
  Research: "调研",
  Script: "脚本",
  "Ready to Film": "待拍摄",
  Filmed: "已拍摄",
  Editing: "剪辑中",
  Review: "待审核",
  Scheduled: "已排期",
  Published: "已发布",
  Analyzed: "已复盘",
  Archived: "存档",
  New: "新",
  Contacted: "已联系",
  Qualified: "已确认意向",
  "Consult Booked": "已约咨询",
  "Consult Done": "咨询完成",
  Deciding: "待决定",
  Won: "成交",
  Lost: "流失",
  Nurture: "培育",
  Priority: "优先",
  Replied: "已回复",
  Negotiating: "洽谈中",
  Active: "进行中",
  Completed: "已完成",
  "Long-term": "长期伙伴",
  "Not Fit": "不合适",
  Planning: "计划中",
  Ended: "已结束",
  Paid: "已支付",
  Locked: "已锁定",
  "Goals Set": "目标已确认",
  "Report Submitted": "已提交报告",
  "Changes Requested": "需修改",
  "Employee Review": "员工确认中",
  Confirmed: "已确认",
  Missing: "未提交",
  Cancelled: "已取消",
};

export function statusLabel(
  language: CompanyOpsLanguage,
  status?: string
): string | undefined {
  if (!status) return status;
  if (language !== "zh") return status;
  return STATUS_ZH[status] || status;
}
